### ISSUE TITLE
IMPORT contact info of all public bodies in Finland

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#1]
UPDATE https://docs.google.com/spreadsheet/ccc?key=0Au5B9VrRkisPdFJkNFVWOVpQaFFLZWYxZjJvcjRvb0E&usp=sharing#gid=0 to 

IMPORT spreadsheet data through http://tietopyynto.fi/admin/. When you have account, ask admin priviledges from @TomiToivio .

Froide can ask email addresses from users, but to make use of the site effcient, we should collect the official email addresses of public sector bodies (State + municipalities). All ideas on how to do this or from where to find the information are more than wellcome.

See instructions on importing the data to Froide: http://froide.readthedocs.org/en/latest/importpublicbodies/

**Comment by pe3** [comment]
Aleksi taisi skreipata Avoimelle ministeriölle kaikkien kirjastojen johtajien sähköpostit. Kuulemma ScraperWikissä. En löytäny vähällä vaivalla.

**Comment by apoikola** [comment]
joo kakkonen lipashti vahingossa, suljin sen.

Froideen pystyy importtaamaan organisaatiot vakiomuotoisesta CSV:stä tai gdocsista http://bit.ly/tietopyynto_fi_organisaatioluettelo

Laitoin nyt allaolevan tietopyynnön http://www.julha.fi/ -palvelua ylläpitävälle väestörekisterikeskukselle. Tämä on datasettinä aika perustavanlaatuinen "luurankodata", joka olisi kiva saada avoimena.

---CLIP---

Pyydän saada sähköisessä muodossa (mieluiten Excel tai csv-tiedosto) luettelon julkishallinnon (valtion ja kuntien) organisaatioista ja niiden kirjaamoiden sähköpostiosoitteista. Alla on lueteltu kaikki tiedot, mitä olen keräämässä:

nimi
    organisaation nimi
email
    kirjaamon sähköpostiosoite
jurisdiction__slug
    lyhenne, jos organisaatiosta käytetään jotain virallista lyhennettä
other_names
    muut organisaatiosta käytetyt nimet
description
    lyhyt tekstimuotoinen kuvaus organisaatiosta
topic__slug
    organisaation toimiala
url
    organisaation verkko-osoite
parent__name
    ylätason organisaatio, mikäli organisaatio kuuluu jonkun muun organisaation alaisuuteen (esim. virasto kuuluu ministeriön alaisuuteen)
classification
    luokittelutieto esim. (valtio, kunnat, ministeriö tms.)
contact
    muut yhteystiedot (sähköpostin ja katuosoitteen lisäksi), esim. puhelinnumero
address
    päätoimipaikan postiosoite

**Comment by apoikola** [comment]
Mitä ilmeisimmin julkishallinnon organisaatioluetteloa ei ole kattavasti olemassakaan. Jatkokeskustelut tähän issueen liittyen [Avoindata.net:n puolella](http://avoindata.net/548/julkishallinon-organisaatiot-valtion-kuntien-kirjaamon)

Odotellessa joku voisi kokeilla, vaikka pienemmällä aineistolla, että miten tuo avausviestissä mainittu importtaus toimii.

**Comment by TomiToivio** [comment]
Mitens tämän operaation kanssa toimitaan?

Virtuaalikone tietopyynto.okf.fi olisi nyt käytettävissä ja testailin Froidea. Ehkäpä isoin puuttuva asia on juuri näiden tietojen kerääminen.

**Comment by apoikola** [comment]
@TomiToivio  Siitä voisi lähteä, että muokkaa noi Gdocsissa Froiden inport-taulukkomuotoon http://www.valtiokonttori.fi/kasikirja/Public/default.aspx?contentId=43620

Kuntia ja muuta voidaan sitten päivittää joukkoistamalla.

**Comment by TomiToivio** [comment]
Pitäisi katsoa onko tästä jo oma issue, mutta Froiden dokumentaatiossa ei sanota tarkemmin serveristä ja tietokannasta? Olisko tavanomaisesti Apache ja PostgreSQL?

**Comment by TomiToivio** [comment]
Testailen Scraperwikillä, mutta regexp ottaa etunimi.sukunimi@domain.fi-osoitteet ilman etunimeä. Ei kukaan tietäisi hyvää regexpiä sähköposteja varten?

``` php
#!/usr/bin/env php
<?

require 'scraperwiki.php';

$html = scraperwiki::scrape("http://www.suomi.fi/rest/organizations/?apikey=/* API KEY TÄHÄN */");
print $html;

$organisaatiolista = simplexml_load_string($html);

$unique_keys = array('name');

    foreach ($organisaatiolista->organization as $organisaatio):
        $lang=$organisaatio->lang;
        $externalurl=$organisaatio['externalurl'];
        $contacturl=$organisaatio['contacturl'];
        $title=$organisaatio['title'];
        $oid=$organisaatio['oid'];
        $name=$title;
        $email="";
        $address="";
        $contact=$contacturl;
        $jurisdiction__slug="";
        $other_names="";
        $description="";
        $topic__slug="";
        $parent__name="";
        $classification="";
        $url=$externalurl;
        $website_dump=scraperwiki::scrape((string)$contacturl);
        $website_dump=strip_tags($website_dump);
        $mailmatches = array();
            $mailpattern = '/[A-Za-z0-9_-]+@[A-Za-z0-9_-]+\.([A-Za-z0-9_-][A-Za-z0-9_]+)/';
            preg_match($mailpattern,$website_dump,$mailmatches);
            $email=$mailmatches[0];
        $request_note="";
        $teksti=array('name'=>(string)$name,'email'=>$email,'address'=>'','contact'=>(string)$contacturl,'jurisdiction__slug'=>'','other_names'=>'','description'=>'', 'topic__slug'=>'','parent__name'=>'','classification'=>'','url'=>(string)$url,'website_dump'=>$website_dump,'request_note'=>'');
        scraperwiki::save_sqlite($unique_keys,$teksti,"organisaatiot");
        echo var_dump($email);
    endforeach;

?>
```

**Comment by TomiToivio** [comment]
On mahdollista scrapettaa sähköpostiosoitteita, mutta nekin pitäisi käydä läpi käsin. Eli ilman käsipeliä saisi ehkä pelkän listan organisaatioista. 

Scraperwiki kaatuu aina kun yritän ladata aineiston, joten leikin sitten PHP:llä.

``` PHP
<?PHP
$handle = fopen("froide.csv", "w");
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://www.suomi.fi/rest/organizations/?apikey=/* API KEY */");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$html = curl_exec($ch);
curl_close($ch);

$organisaatiolista = simplexml_load_string($html);

foreach ($organisaatiolista->organization as $organisaatio):
$lang=$organisaatio->lang;
$externalurl=$organisaatio['externalurl'];
$contacturl=$organisaatio['contacturl'];
$title=$organisaatio['title'];
$oid=$organisaatio['oid'];
$name=$title;
$email="";
$address="";
$contact=$contacturl;
$jurisdiction__slug="";
$other_names="";
$description="";
$topic__slug="";
$parent__name="";
$classification="";
$url=$externalurl;
$website_dump="";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, (string)$contacturl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$website_dump = curl_exec($ch);
curl_close($ch);
$website_dump=strip_tags($website_dump);
$mailmatches = array();
$mailpattern = '/[A-Za-z0-9_-]+@[A-Za-z0-9_-]+\.([A-Za-z0-9_-][A-Za-z0-9_]+)/';
preg_match($mailpattern,$website_dump,$mailmatches);
$email=$mailmatches[0]; 
$request_note="";
$teksti=array((string)$name,(string)$email,'',(string)$contacturl,'','','','','','',(string)$url,(string)$website_dump,'');
echo (string)$email;
fputcsv($handle, $teksti);
endforeach;

fclose($handle);
?>
```

**Comment by TomiToivio** [comment]
Itse asiassa käyttäjä voi ehdottaa viranomaista tehdessään tietopyynnön tai joku muu voi lisätä sen myöhemmin. 

Eli ei siihen varmaan edes tarvitse mitään valtavaa viranomaislistaa että saa käyttökelpoisen sivuston.

**Comment by TomiToivio** [comment]
Sen sijaan voisi olla tärkeämpää kerätä ne lait, joihin tietopyynnöt perustuvat?

**Comment by apoikola** [comment]
Näkisin aika tärkeänä, että olisi melko kattava siemenaineisto virastoista, esim

tämä: http://www.valtiokonttori.fi/kasikirja/Public/default.aspx?contentId=43620
+
tämä: http://www.kunnat.net/fi/Yhteystiedot/kunta-alan-yhteystiedot/kunnat/Sivut/default.aspx

Sen jälkeen täydennykset ja ylläpito joukkoistamalla.

Lainsäädäntö on tämän suhteen Suomessa yksinkertainen, kaikki tietopyynnöt pohjautuvat julkisuuslakiin: http://www.finlex.fi/fi/laki/ajantasa/1999/19990621

**Comment by apoikola** [comment]
@TomiToivio kyselit, mitä kaikkea dataa virastoista tarvitaan, niin

1) Kunnan nimi
2) Sähköposti
3) URL ( Joillain kunnilla ei näemmä ole 
4) Puhelinnumero

kombolla pääsee hyvin alkuun, en nyt muista mitä kaikkea muuta Froide-importmuodossa oli mahdollista tuoda, mutta ainakaan website dumppia ei nyt tarvita

**Comment by TomiToivio** [comment]
Kunnat taitavat olla ainoita joista saa yhteystiedot ilman että joku tekee sen suurimmaksi osaksi käsin. :)

**Comment by apoikola** [comment]
Katoitko sen valtion virastojen Excelin, muistaakseni sielläkin oli
yhteystiedot ihan suht koht kondiksessa.
- Antti Poikola - from mobile device -

**Comment by TomiToivio** [comment]
Mitäs jos laitetaan Froide kaapimaan kaikkea ihan itse: https://github.com/stefanw/froide-foiidea

**Comment by apoikola** [comment]
Kaikkea voi toki kokeilla, mutta uskon, että valtion Excel + kunnat + joukkoistettu täydentäminen vievät jo pitkälle ilman kaapimistakin.

**Comment by TomiToivio** [comment]
Laitoin nyt kunnat Froideen: https://docs.google.com/spreadsheet/ccc?key=0Aj43IrSC4ctBdFBFTXh0SG5rVWhxLWdreG1oX1F0Smc&usp=sharing

**Comment by TomiToivio** [comment]
Mitäs jos vaan dumppaa Suomi.fi APInkin sinne: https://docs.google.com/spreadsheet/ccc?key=0Aj43IrSC4ctBdDYtTkFIYUM4Vjl5VWRBa0piVlRwQ1E&usp=sharing

Sivuilta scrapetut sähköpostiosoitteet ovat aika satunnaisia ja kaikki organisaatiot eivät taida kuulua Froideen. Niitä voi kumminkin joukkoistaa sitä mukaa kun tietopyyntöjä alkaa tulla, skripteillä ei pääse tuon pidemmälle eikä kukaan näytä editoivan noita Google Docsissa.

**Comment by TomiToivio** [comment]
Nyt siellä on 977 "viranomaista", joista 544 omistaa ainakin jonkun sähköpostiosoitteen. On vaan aika usein luokkaa etunimi.sukunimi@viranomainen.fi. 

Kunnat sai scrapettua hyvin: http://tietopyynto.fi/yksik%C3%B6t/aihe/kunta/

Tuolta voisi napsia helposti kolmannen sektorin toimijat pois seasta, mutta kuka jaksaa kaivella sähköpostit käsin lopuille viranomaisille?

Nyt sähköpostittomat organisaatiot eivät ole ollenkaan näkyvissä. Tämä olisi paljon helpompaa jos voisi kaivaa sähköpostin vasta kun joku tekee oikeasti tietopyynnön.

**Comment by apoikola** [comment]
Suomi.fi -kamaa ei kannata mielestäni Froideen laittaa, se vaan hämään, jos siellä on ylimääräisiä (ei julkisuuslain mukaisioa organisaatioita). Jos sieltä puuttuu joku, minkä pitäisi olla, niin aina voi lisätä, mutta ylimääräisisitä voi olla oikeasti haittaa.

Siirsin kunnat nyt myös tuonne: (FROIDE Kunnat)
http://bit.ly/tietopyynto_fi_organisaatioluettelo

Tein välilehdelle FROIDE Valtionkonttori ristiin taulukoinnin, jossa on Valtionkonttorin luettelo (kaikki kuuluvat julkisuuslain piiriin) ja jos Suomi.fi:stä löytyi samalla nimellä niin sitten se. Noihin voisi Suomi.fi API:n kautta hakeas Description -sarakkeeseen täydennystä.

Voiko sähköpostittomille organisaatioille laittaa pseudomeiliosoitteen tyyliin etsi.osoite@googlettamalla.fi , jotta ne saisi ainakin näkyviin Froidessa?

**Comment by TomiToivio** [comment]
Spreadsheetit pitää muuten importtaa komentoriviltä, en ainakaan saanut toimimaan administa.

**Comment by apoikola** [comment]
Nyt kun loggasin sisään, niin tosiaan heti vähän hämäsi Bird Life ry ja Avoin ministeriö, eli ennen kuin laajemmin lähdetään käyttämään, niin kannan voisi tyhjentää ja viedä sinne vain julkisuuslain mukaisia tietopyyntöjen kohdeorganisaatioita.

Miten muuten testauksen kanssa edetään, onko kanta tarkoitus jyrätä, vai jääkö testipyynnöt yms. näkyviin.

**Comment by TomiToivio** [comment]
Nythän siellä on jo oikeita tietopyyntöjä ja oikeita vastauksia, joten ei varmaan kannata enää jyrätä.

**Comment by TomiToivio** [comment]
Joku sanoi että olisi hyvä jos tietopyynnön voisi tehdä myös muille kuin viranomaisille? Pitäisikö siellä sitten olla ainakin toinen lainsäädäntö, koska tietopyyntö epäviranomaiselle ei varmaankaan perustu mihinkään lakiin?

**Comment by apoikola** [comment]
Teletunnistetietoja voi pyytää teleoperaattoreilta, mutta en sotkisi niitä nyt tähän, helpompi fokusoida tämä palvelu nimenomaan julkisuuslain mukaisiin tietopyyntöihin, jotka kohdistuvat julkisiin organisaatioihin, eli yhdistykset pitää jollain tavalla saada kannasta pois.

## 

Sähköisen viestinnän tietosuojalaki 37 §
Käyttäjän erityinen tiedonsaantioikeus

Käyttäjällä on oikeus saada teleyritykseltä tämän hallussa olevat tunnistamistiedot, jotka ilmaisevat liittymän tai päätelaitteen sijainnin tietyllä hetkellä.

**Comment by TomiToivio** [comment]
Täällä on Froidesta exportattu nykyinen viranomaislista CSV-muodossa: https://docs.google.com/spreadsheets/d/1NuIHD71ByVHP5EmfGMUc2-S-pooDLQz2OGAdd5ax180/edit?usp=sharing

Se on ainakin ajan tasalla ja oikeassa formaatissa. Tosin käyttäjät voivat tehdä lisää viranomaisia, joten se ei välttämättä ole ajan tasalla kovinkaan kauan. 

Loppujen lopuksi näiden editoiminen suoraan Froiden administa ei ole sen vaikeampaa kuin spreadsheetin editoiminen, mutta sitten kaikilla editoijilla pitäisi olla admin-tunnarit: http://tietopyynto.fi/admin/publicbody/publicbody/

**Comment by apoikola** [comment]
## Hyvä! Allaolevaa viestiä saa levittää omissa kanavissaan:

Talkoistuspyyntö hyvän asian puolesta: Tietopyynto.fi -sivun viranomaisrekisterissä on nyt ylimääräisiä ei-julkisuuslain alaisia organisaatioita ja julkishallinnon organisaatioista monilta puuttuu kirjaamon sähköpostiosoite. Tavoite on, että tietokanta saadaan joukkoistamalla siivottua. Yhdenkin tiedon päivittäminen oheiseen taulukkoon auttaa!

http://okf.fi/tietopyynto-osoiterekisteri

**Comment by opottone** [comment]
Kattavan viranomaislistan laatiminen on muuten mahdoton tehtävä jo senkin takia, että jossain tapauksissa on epäselvää onko joku organisaatio viranomainen vai ei (julkisuuslain mielessä). Esimerkiksi tässä tapauksessa oikeuskansleri totesi, että asia voidaan tulkita kummin päin vain: [OKV/1078/1/2011](http://www.finlex.fi/fi/viranomaiset/foka/2013/20131970). Jos ylin laillisuusvalvoja ei osaa antaa yksikäsitteistä vastausta, niin tuskin mekään siinä onnistumme.

**Comment by TomiToivio** [comment]
Missäs vaiheessa viranomaislistan kanssa mennään? Näitä pitää ajaa skriptillä tietokantaan sitten kun lista on kohtuullisen valmis.

**Comment by apoikola** [comment]
Voisin yrittää saatella tämän maaliin tiistaina 18.11. OKF:n working group
-päivän yhteydessä.

2014-11-10 12:11 GMT+02:00 Tomi Toivio notifications@github.com:

> Missäs vaiheessa viranomaislistan kanssa mennään? Näitä pitää ajaa
> skriptillä tietokantaan sitten kun lista on kohtuullisen valmis.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/1#issuecomment-62364311.

## 

+358 44 337 5439
about.me/apoikola

**Comment by apoikola** [comment]
tänään huutelin netissä ja jonkun verran sainkin apua osoiterekisterin joukkoistamiseen. Itse vietin sen parissa muutaman tunnin ja turnauskestävyys alkaa nyt hiipua. Melkolailla valmista kuitenkin jo on. Tässä ehdotukseni jatkoon:

@TomiToivio :
- voit viedä vihreällä taustalla olevat valmiit rivit tietokantaan (OK sarakkeessa merkintä K)
- olisi jees, jos vähintäänkin classification sarakkeen tiedon saisi mukaan ja myös kommenttisarakkeen, jos vain onnistuu jotenkin?
- kun nämä on viety kantaan , niin pingaa minulle ja poistetaan ne joukkoistamistaulukosta häiritsemästä.

Muut:
- punaisella pohjalla on joko puuttuvia kirjaamo-osoitteita esm. sairaanhoitopiirit tai puuttuva tieto siitä, onko kyseessä julkisuuslain alainen organisaatio. Näitä saa selvittää ja viedään kantaan sitten seuraavassa rykäisyssä lisää valmistuneita.
- OK sarakkeessa "Myöhemmin" merkinnällä on sellaiset ei-julkishallinnon organisaatiot, joille on meiliosoite, niihin ei siis päde julkisuuslaki, joten niitä ei pidä sotkea julkisuuslain mukaisiin tietopyyntöihin, mutta jos haluamme voimme myöhemmin laajentaa palvelua koskemaan muitakin, kuin julkishallinnon julkisuuslain alaisia organisaatioita.

Linkit:

-> Joukkoistustaulukko http://okf.fi/tietopyynto-osoiterekisteri

**Comment by TomiToivio** [comment]
Pitäisköhän näitäkin jo laittaa tietokantaan...

**Comment by apoikola** [comment]
pitäisi

**Comment by apoikola** [comment]
ping @TomiToivio tämä olisi closausta vaille valmis, jos importtaus onnistuisi.

**Comment by TomiToivio** [comment]
Ei vaan jaksaisi tunkea niitä skriptillä tietokantaan, kun siellä on jo oikeaakin sisältöä.

**Comment by apoikola** [comment]
Kaikki kannassa ollut oikea sisältö osoiterekisterin osalta on myös tuolla taulukossa, eli taulukon datalla voi osoiterekisterin osalta jyrätä kannassa olevan. Taulukkoon on sen lisäksi päivitetty huomattava määrä uusia ja tarkistettuja osoitteita. Idea, että tämän jälkeen ylläpito olisi suoraan kantaan admin-käyttiksen kautta.

**Comment by jaakkokorhonen** [comment]
Etunimi.sukunimi -osoitteet pitää poistaa.
Mites, poistetaanko osoitteettomatkin?

**Comment by apoikola** [comment]
Tarkistin nyt http://okf.fi/tietopyynto-osoiterekisteri vihreällä taustalla (OK sarakkeessa K) on kaikissa osoite ja poistin joukosta ne kaksi, joissa oli etunimmi.sukunimi, eli ne ovat nyt sisään vietävissä.

Oma suositukseni olisi, että kaikki muut poistettaisiin tässä vaiheessa ja niitä voi sitten lisätä manuaalisesti tarpeen mukaan.

**Comment by jaakkokorhonen** [comment]
Niin se varmaan on parempi pistää hommalle joku piste tässä yhteystietoasiassakin, ja poistaa nimettömät.

**Comment by TomiToivio** [comment]
Mietin juuri miten cvs-tiedoston versioita saisi vertailtua järkevimmin. :)

**Comment by TomiToivio** [comment]
Eli päivitän kaikki, jotka on merkitty tietokantaan vietäväksi ja tipautan kaikki muut toistaiseksi pois: https://docs.google.com/spreadsheets/d/1NuIHD71ByVHP5EmfGMUc2-S-pooDLQz2OGAdd5ax180/edit#gid=1152992410

**Comment by TomiToivio** [comment]
Importtasin, täällä on Tietopyynnön nykyinen viranomaislista: https://docs.google.com/spreadsheets/d/1NOmxVSYBThD5ZQ278nwn8-M7wxf9pvgVSCrqHTs1G3s/edit?usp=sharing

**Comment by TomiToivio** [comment]
Tämän voi varmaankin sulkea.
