### ISSUE TITLE
Set to use Apache or other web server

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#10]

**Comment by TomiToivio** [comment]
What about the database? PostgreSQL?

**Comment by TomiToivio** [comment]
Tämä pyörii nyt Apachella ja SQLitellä: http://tietopyynto.okf.fi/

Seuraava kysymys onkin tietokanta. Oletusarvoinen SQLite ei ehkä ole kovin järkevä muuhun kuin testikäyttöön. Sync/migrate MySQLiin bugaa ja Postgresiä en edes kokeillut vielä.

Mitäs tehdään?

**Comment by apoikola** [comment]
itselläni ei ole mitään käryä tietokantojen hyvistä ja huonoista puolista, eikä Froiden dokumentaatiokaan pahemmin antanut ajatuksia http://froide.readthedocs.org/en/latest/productionsetup/

olisiko @juyrjola sulla ehdotuksia?

**Comment by juyrjola** [comment]
Postgres on yleensä aika varma valinta. Voin heittää kannan asennusloitsut tarvittaessa.

**Comment by TomiToivio** [comment]
Postgres tosiaan toimii.

**Comment by TomiToivio** [comment]
Froide muuten kaatuilee kuormitustesteillä Apachella out of memory erroreihin.

Kyselin Stefanilta pitäisikö ottaa Apachen tilalle Gunicorn/Nginx.

**Comment by apoikola** [comment]
vastasinkin jo meilissä, mutta hyvä keskittää jatkossa keskustelu tänne
githubiin.

2014-06-07 18:01 GMT+03:00 Tomi Toivio notifications@github.com:

> Froide muuten kaatuilee kuormitustesteillä Apachella out of memory
> erroreihin.
> 
> Kyselin Stefanilta pitäisikö ottaa Apachen tilalle Gunicorn/Nginx.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/10#issuecomment-45412177.

## 

+358 44 337 5439
about.me/apoikola

**Comment by TomiToivio** [comment]
Ongelma näyttäisi olevan se että keskustelu ei keskity oikein mihinkään.

**Comment by TomiToivio** [comment]
Lienee pakko lisätä serverin muistia joka tapauksessa. Djangolle suositeltu 3 gigaa ei sittenkään ole mikään vitsi.

**Comment by TomiToivio** [comment]
Muistia tuli lisää ja nyt se ei ainakaan kaadu muistin puutteeseen.
