### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#107]
Froide on Open Knowledgen avoimen lähdekoodin projekti. Jos haluat tukea Froiden kehittämistä, vieraile GitHub -sivullamme ja Holvi-verkkokaupassamme. Vertaistukea tietopyytämiseen saat Facebook-ryhmästämme. https://www.facebook.com/groups/tietopyynto

**Comment by hylje** [comment]
toteutettu ja jalkautettu
