### ISSUE TITLE
Set to use Haystack for search

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#11]

**Comment by TomiToivio** [comment]
Onko merkitystä mikä hakukone on käytössä: http://django-haystack.readthedocs.org/en/latest/installing_search_engines.html

**Comment by TomiToivio** [comment]
Haystack toimii nyt Elastisearchilla: http://django-haystack.readthedocs.org/en/latest/installing_search_engines.html#elasticsearch

**Comment by TomiToivio** [comment]
Itse asiassa Froide taitaa käyttää ilman muutoksia joka tapauksessa SimpleSearchia. Taitaa toimia ihan tarpeeksi hyvin sekin.
