### ISSUE TITLE
Liite ei aukea: Forbidden  You don't have permission to access

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#114]
http://tietopyynto.fi/r/557 avattaessa https://tietopyynto.fi/files/foi/2244/Investiumoydiaariote.pdf
<img width="638" alt="screenshot 2018-03-05 11 59 58" src="https://user-images.githubusercontent.com/3482497/36969113-3d2bff48-206d-11e8-9201-c337d87095cf.png">

**Comment by AleksiKnuutila** [comment]
Kiitos huomiosta, korjattu.
