### ISSUE TITLE
Valtakunnansyyttäjänviraston sähköpostiosoite on muuttunut

### ISSUE THREAD

**Issue by JanneKN** [okffi/tietopyynto#115]
Yritin tehdä tietopyynnön valtakunnansyyttäjävirastoon ja kuittauksena tuli että syyttäjälaitoksen organisaatiouudistuksen myötä sähköpostiosoite  vksv@oikeus.fi on poistettu käytöstä. Lähettämänne viesti on välitetty uuteen osoitteeseen valtakunnansyyttaja.syyttaja@oikeus.fi. Pyydämme Teitä jatkossa lähettämään viestinne edellä mainittuun uuteen osoitteeseen. Edelleenvälitystoiminto poistetaan käytöstä 31.12.2019.

Tämän jälkeen tuli kuitenkin kuittaus valtakunnansyyttaja.syyttaja@oikeus.fi on vastaanottanut viestin. Vaikuttaisi, että edelleenvälitystoiminto toimii edelleen. Ehkä osoite pitäisi kuitenkin vaihtaa siltä varalta, että edelleenvälitys lakkaa jossain vaiheessa toimimasta.

**Comment by JanneKN** [comment]
Vielä täsmennyksenä edelliseen, että valtakunnansyyttäjänvirastoa ei ole enää olemassa, vaan lokakuussa 2019 tuli organisaatiomuutos, jonka seurauksena tuli valtakunnansyyttäjän toimisto. https://syyttajalaitos.fi/organisaatiouudistus

Samalla muutkin syyttäjän organisaatioon liittyvät nimet ja varmaan myös yhteystiedot pitäisi korjata. Esimerkiksi ei ole enää olemassa Itä-Uudenmaan syyttäjänvirastoa vaan se on osa Etelä-Suomen syyttäjäaluetta. Nyt näyttäisi siltä, että kun Itä-Uudenmaan syyttäjänvirastoon yrittää tehdä tietopyyntöä, niin kirjaamosta ei tule kuittausta, eli vaikuttaa, että se ei mene perille.

Eli voisitteko samalla korjata nämä kaikki syyttäjälaitoksen tiedot oikeiksi?

**Comment by tarmot** [comment]
Muutos tehty.
