### ISSUE TITLE
Configure and test the email settings

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#12]

**Comment by TomiToivio** [comment]
Mitäs käytetään?

**Comment by jaakkokorhonen** [comment]
http://okf.fi/server sanoo:
SMTP
smtp.saimanet.net

**Comment by TomiToivio** [comment]
Tarkoitin että tarvitaanko jotain tämän tyyppistä viritelmää sähköpostin vastaanottamiseen (lähettää se kyllä osaa): http://froide.readthedocs.org/en/latest/herokudeployment/#set-up-email-sending-and-receiving

**Comment by TomiToivio** [comment]
Froide siis lähettää sähköpostit ulos ihan tavallisesti SMTP:llä, mutta tietopyyntöjen vastausosoitteet ovat yksilöllisiä tyyliin "t.toivio.uugb3t9nud@tietopyynto.okf.fi" tai "t.toivio.h59hy9ents@tietopyynto.okf.fi".

Eli kaikki domainiin tulevat sähköpostit pitäisi ohjata IMAP-laatikkoon, josta Froide tunnistaa ne vastausosoitteen perusteella.

**Comment by apoikola** [comment]
Mites tuo Postmark? Jos se helpottaa ylläpitoa, niin ei se varmaan meidän alkuvolyymeilla kovin kalliiksi tule https://postmarkapp.com/pricing

**Comment by TomiToivio** [comment]
Kai tämän imapinkin saisi tehtyä helpommin jotain kautta: http://froide.readthedocs.org/en/latest/configuration/#settings-for-sending-e-mail

**Comment by TomiToivio** [comment]
Sähköpostin toimivuus olisi vain syytä testata kunnolla ennen kuin sinne laittaa ihan oikeita viranomaisia, joten tämä lienee tällä hetkellä tärkein asia?

**Comment by TomiToivio** [comment]
No sain lopultakin mailit toimimaan IMAPin kautta.

**Comment by jaakkokorhonen** [comment]
Hienoa.

**Comment by TomiToivio** [comment]
Tausta-ajot toimivat siis Celeryllä/RabbitMQ:lla: http://froide.readthedocs.org/en/latest/gettingstarted/#background-tasks-with-celery

Näillä on merkitystä lähinnä sähköpostien lukemisen kannalta.

**Comment by jaakkokorhonen** [comment]
resolved and tested
