### ISSUE TITLE
Transfer the tietopyynto.fi domain for OKFFI

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#13]
Currently @apoikola has paid and owns / controls the domain. How can I transfer this to OKFFI? ping @tarmot @jaakkokorhonen

**Comment by tarmot** [comment]
Luot ficorassa tai dns-välittäjäsi palvelussa siirtoavaimen, jonka kerrot minulle. Sen perusteella voin siirtää domainin okf:n ficora-tilin haltuun.

**Comment by apoikola** [comment]
löysin Ficoran postittaman lapun, missä valtuutusavain (lienee sama, kuin siirtoavain?) - laitoin meilitse sinulle. Tällä haavaa domain voinee osoittaa tänne Github pagesiin A ja WWW 204.232.175.78 MX tietopyynto.fi

Kun @vikoivun saa laitettua Froiden kiinni Apacheen, niin sitten sen voinee ohjata sinne https://github.com/okffi/tietopyynto/issues/10

**Comment by apoikola** [comment]
@tarmot meilitse 18/12/2014 "Jes, sain kopin. Tunnus kuitenkin näyttää olevan henkilölle tehty, ei organisaatiolle. En ole varma, saanko sinun nimesi siivottua sieltä pois. Mutta DNS:n päivitys kyllä onnistuu. Teen sen varmaan sitten, kun tehdään kytkentä froideen. Let me know."

Eli tänne vaan muistiksi, että Tarmoa pitää pingata sitten, kun Froide on pystyssä ja joku IP, mihin ohjata.

**Comment by TomiToivio** [comment]
Tietopyynto.fi tarvitsee varmaankin SSL-sertifikaatin?

Lisäksi tarvitaan tämä domainin sähköpostien ohjaaminen IMAP-laatikkoon: https://github.com/okffi/tietopyynto/issues/12

**Comment by tarmot** [comment]
Saako siis nyt ohjata domainin uudelle serverille? Onko se uusi serveri valmis ottamaan vastaan liikenteen?

**Comment by TomiToivio** [comment]
Pointti lienee siinä että sähköpostien ohjausta on vaikea testata muuten. Eli demona se käytännössä ainakin jonkin aikaa pyörisi? 

Vai pitäisikö laittaa nämä serverille placeholderiksi ja jemmata Froide: http://tietopyynto.fi/

**Comment by tarmot** [comment]
No, kunhan olette tehneet päätöksen, kertokaa kun dns-muutos pitää tehdä.

**Comment by apoikola** [comment]
Demona pyörittäminen on varsin ok, pääasia, että päästään kokeilemaan. En ihan ymmärtänyt Placeholderideaa, mutta @TomiToivio luotamme sinuun, mikä vaan fiksuimmalta tuntuu :)

**Comment by TomiToivio** [comment]
Mielestäni domainin voi siirtää.

Tarvitaan myös sähköpostin ohjaus ja subdomain imap.tietopyynto.fi?

**Comment by TomiToivio** [comment]
Voikos tietopyynto.fi -domainin siis ohjata IP-osoitteeseen 159.255.193.72?

Tyyliin:
@ A 159.255.193.72
@ MX 159.255.193.72
IMAP A 159.255.193.72

**Comment by tarmot** [comment]
Ilmeisesti halutaan myös eroon louhi:n dns:stä?

Jos kyllä, niin OKFFI joutuu ostamaan dns-palvelut tälle domainille. Menee pieni hetki.

Jos ei, niin se henkilö, joka hallinnoi tuon domainin dns:ää louhissa, voi tehdä tuon muutoksen.

**Comment by jaakkokorhonen** [comment]
Nyt voidaanko nyt lakkaa säätämästä, jos jogi vain siirtäis domainin? Tää on jotain 90-lukua että heti kun on vakiosta poikkeava ympäristö, käynnistyy hillittömät sähköpostiketjut.

Eli tarvitaan @apoikola sinulta siirtoavain jolla voidaan siirtää hallinnointi okffi:lle. 

Minä ja tarmo tiedotetaan Saimaa, joka lisää merkityt domainit dns:ään, ja me siirretään domain siirtoavaimella sekä rekisteröidään uusi dns.

Tuo muuten sitten laitetaan pointtaamaan 159.255.193.67 koska on sovittu että dns-pointtaukset hallinnoidaan avohoidon apachessa. Säädön välttämiseksi.

**Comment by tarmot** [comment]
Rauhoitu, Jaakko. Siirtoavain on jo minulla eli voin vaihtaa dns-palvelimet. Mutta en voi tehdä vaihtoa ennen kuin Saima lisää tämän domainin meidän dns:ään. Nyt siis odotetaan ihan 90-lukuisesti saimanetin helpdeskin reagoimista asiaan.

Mutta miksi se pistetään .67:aan, kun kerran on käytössä ihan erillinen serveri tietopyynto.fi:lle? Et kai ajatellut tehdä reverse proxya kuitenkaan?

**Comment by jaakkokorhonen** [comment]
ok jos @tarmot on hoidossa niin se tieto riittää minulle. sorry avautuminen tämän laukasi kun käytin yli tunnin selvittääkseni mitä tapahtuu enkä vieläkään tiedä.

tietopyynto.okf.fi on tietenkin hallinnoitu avohoidon apachessa mutta jos tietopyynto.fi ei onnistu samaan tyyliin niin sitten laitetaan tietty sinne omaan.

tehdään imap.okf.fi kuitenkin, niin pysyy ylläpidettävien komponenttien määrä meidän kokonaisuudessa jotenkin järkevänä.

**Comment by tarmot** [comment]
Nyt on DNS tehty. Laitoin nyt A-recordit osoittamaan .72-osoitteeseen. Mutta jos on syytä ohjata pääserverille joko web-liikenne tai imap-etuliite tai mx:t, kertokaa.

**Comment by TomiToivio** [comment]
Kiitos! Mukavaa kun kaikkien projektien viestintä on eri paikoissa, en huomannut tätäkään ennen kuin nyt.
