### ISSUE TITLE
Test the Heroku Deployment

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#14]
Deploying Froide has become significantly easier over the last weeks and is now even documented.

The Heroku deployment guide is here:
http://froide.readthedocs.org/en/latest/herokudeployment/

**Comment by apoikola** [comment]
Following the Heroku deployment instructions http://froide.readthedocs.org/en/latest/herokudeployment/ I managed to set up http://tietopyynto.herokuapp.com/
1. Postmark problem...   I could not figure out how to follow this instruction "You should change these URLs through the SECRET_URLS setting of Froide." therefore http://tietopyynto.herokuapp.com/postmark/postmark_bounce/ gives 404 error
2. Attachment storage from Amazonilta not yet set up
3. I followed the instructions on how to set up Translations, but for some reasons only English works

Osaisitko auttaa kohtien 1 ja 3 kanssa?

**Comment by TomiToivio** [comment]
Kyllä käännökset saa toimimaan pienellä säätämisellä. Maakohtaisten kielikoodien (esim. fi-fi) kanssa näyttäisi olevan ongelmia. Eli Transifexista tulee kielikoodit joita Django ei ymmärrä.

**Comment by jaakkokorhonen** [comment]
obsolete
