### ISSUE TITLE
Ansible playbook for automated deployment

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#15]
Review possibility of making a Ansible playbook for automated deployment

**Comment by jaakkokorhonen** [comment]
We will use docker when OKFN has released that as part of D-CENT project.

**Comment by apoikola** [comment]
Docker and Ansible are not the same (options for each others) they work best together http://www.ansible.com/docker

**Comment by TomiToivio** [comment]
Asentelin ton Ansiblen, mutta en oikein tiedä mitä se pitäisi laittaa tekemään. Lisäksi parilla sen kilpailijalla näytti olevan enemmän näihin projekteihin sopivia lisäosia.

**Comment by TomiToivio** [comment]
http://ryandlane.com/blog/2014/08/04/moving-away-from-puppet-saltstack-or-ansible/

**Comment by jaakkokorhonen** [comment]
Hei tämä ei ole projektin scopessa, vaan ihan erillinen homma. Meillä on muutenkin liian pieni budjetti. Ei ole yleinen käytäntö käydä availemassa tehtäviä ohi projektipäällikön, toivottavasti tätä ei enää tapahdu.

**Comment by apoikola** [comment]
Avoin projekti avoin backlog, kaiken ei tarvi mahtua juuri nykyiseen buduun ja skopeen, mutta ei relevantteja issueita kannata sulkea, jos niitä ei ole ratkaistu tai päätetty, ettei koskaan toteuteta.

**Comment by apoikola** [comment]
Milestonet on hyvä työkalu valita avoimista issueista ne, mihin keskitytään juuri nykybudjetilla, niin silloin voi jättää matakamman prion jutut odottamaan.parempaa päivää.

**Comment by TomiToivio** [comment]
Näyttää vain sille, että Ansible tekisi hommasta itse asiassa monimutkaisemman. Jos Froiden kaltaisia saitteja olisi yli 10, voisi siitä olla jotain apuakin. Tässä vaiheessa se vain lisäisi monimutkaisuutta.

Lisäksi Froide on selvästi niin kokeellisessa vaiheessa, että asetuksia joutuu todellakin virittelemään kantapään kautta. Siihen ei välttämättä olisi yhtään helppoa tehdä asetuksia automaattisesti. Tarvittaisiin ensin selkeämpi virallinen dokumentaatio Froiden asentamisesta tuotantokäyttöön.
