### ISSUE TITLE
Document the Froide installation to readme

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#16]
Froiden asennus avohoito.okf.fi-palvelimella
Asennus on tehty kokonaisuudessaan /srv/froide -hakemiston alle.

Itse ohjelmisto on asennettu http://froide.readthedocs.org/en/latest/gettingstarted/ -ohjeen mukaan hakemistoon /srv/froide/software

Ohjeiden mukaan tehty virtualenv löytyy hakemistosta /srv/froide/environment (siellä on myös /srv/froide/environment/logs -joka liittyy virtualenvwrapperiin)

Paikallinen djangon asetuscustomointin on tiedostossa: /srv/froide/software/froide/local_settings.py
tätä kirjoittaessa ainoa muutos siellä on PostgreSQL-kannan käyttöön otto.

PostgreSQL-kanta on luotu vakiokomennoilla, UTF-8 kollaatiolla. Kannan nimi, käyttäjätunnus ja salasana ovat:
froide (oletan että PostgreSQL kuuntelee vain paikallista konetta)

**Comment by pe3** [comment]
Todella hienoa, että asennus on dokumentoitu.

**Comment by apoikola** [comment]
settings.py yms. konffitiedostot olisi kyllä hyvä versioida githubiin varsinkin, jos muutoksia enemmänkin, kuin vain yhdessä tiedostossa ja yhdellä rivillä

**Comment by TomiToivio** [comment]
Tungen kaiken Bitbucketin privaattirepoon, koska siellä on ilmaiset privaattirepot. Settings.pyssä on nimittäin salasanoja ja muuta kivaa, jota ei voi laittaa julkiseen repoon.

**Comment by apoikola** [comment]
@TomiToivio OKFFI:lla on myös Githubiin ilmaisia privaattirepoja 5 kpl (NGO diili), voisi olla parempi pitää kaikki Githubissa - tein nyt privarepon https://github.com/okffi/sysadmin johon sulla ja @jaakkokorhonen oikeudet.
