### ISSUE TITLE
Set up application / server monitoring

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#17]
Nagios or some other system which sends email notifications to sysadmins if something goes wrong.

**Comment by TomiToivio** [comment]
Laitoin jo joitain joita käytän yleensäkin:
- Logwatch
- Fail2ban (SSH bruteforcettajat ärsyttävät)
- Pingdom

Onko esimerkiksi Nagios tarpeen? 

Tarvitaanko tähän jaettu tili esimerkiksi Google Analyticsiin? Tai vaikka Piwik jos tahdotaan olla NSA-vapaita.

**Comment by TomiToivio** [comment]
Ainakin on nyt Nagios: http://tietopyynto.fi/nagios3/

**Comment by tarmot** [comment]
nagiosin ehkä kannattaisi olla muualla kuin siinä valvottavalla serverillä. Jos palvelin menee nurin, valvonta menee samalla. Mutta jossain voisi olla jaossa nuo nagios-snippetit.

**Comment by TomiToivio** [comment]
Ehkäpä sen Tietopyynnölle asennetun Nagioksen voi ottaa pois?

**Comment by tarmot** [comment]
http://status.okf.fi on nyt käytössä. Sinne vaan tietopyyntö-serverinkin palvelut valvontaan. Ohjeet okf.fi/server

**Comment by jaakkokorhonen** [comment]
![screenshot 2015-01-09 01 40 12](https://cloud.githubusercontent.com/assets/3482497/5673112/7f0bf3ea-97a0-11e4-966e-e5621970f7ee.png)
