### ISSUE TITLE
Suomennosten parantelu ja infosivujen sisältö

### ISSUE THREAD

**Issue by TomiToivio** [okffi/tietopyynto#19]
http://tietopyynto.fi/ on vielä puutoksia suomennoksissa ja joiltain informaatiosivuilta puuttuu sisältö.

**Comment by TomiToivio** [comment]
Lisäksi pitäisi tehdä templaatit tietopyyntöjen sähköposteille jne.

**Comment by jaakkokorhonen** [comment]
Footerin urlit oli päin honkia:    Tietoja palvelusta    Apua    Käyttöehdot    Tietosuojakäytännöt

pitäis olla:
Tietoa palvelusta
Ohje
Käyttöehdot
Rekisteriseloste

päivitin nyt Transifexiin, mut pitääkö @TomiToivio  muuttaa urleja djangossa tms?

Eli laitoin nyt transifexiin urlit: 
tietoa-palvelusta
ohje
kayttoehdot
rekisteriseloste

**Comment by jaakkokorhonen** [comment]
Voitko ajaa @TomiToivio transifexin tietopyyntöön niin tsiigataan miltä näyttää?

**Comment by TomiToivio** [comment]
Laitoin pari tuntia sitten.

**Comment by jaakkokorhonen** [comment]
outoa, esim "yleishyödyllistä, tiedon vapauteen liittyvä pyyntö" on edelleen " yleishyödyllistä tietoa (tiedon vapauteen liittyvä pyyntö)" Sitte jotku tekstit on päivittyneet.

**Comment by TomiToivio** [comment]
Ihan kuin Transifex bugais jotenkin, koska osa vähän aikaa sitten tekemistäni muutoksista puuttuu.

**Comment by TomiToivio** [comment]
Ihan kuin Transifex ei toimisi kuten pitäisi.

**Comment by TomiToivio** [comment]
Suomentaa urlit niin kaikki bugaa: http://tietopyynto.fi/apua/sinun-yksityisyytesi/

**Comment by TomiToivio** [comment]
Jaahas, menee sekaisin Froide ja Froide-2.

**Comment by TomiToivio** [comment]
Mitenköhän nää yhdistetään:
https://www.transifex.com/projects/p/froide/language/fi_FI/
https://www.transifex.com/projects/p/froide-2/language/fi/

**Comment by jaakkokorhonen** [comment]
jaahas vai että froide-2

**Comment by jaakkokorhonen** [comment]
varmaan niin että vetää exceliin vierekkäisiin sarakkeisiin ja dellaa aina huonomman joka riviltä

**Comment by jaakkokorhonen** [comment]
mä voin dellailla läpi jos jaksat duunaa excelin ja importtaa takas transifexiin

**Comment by TomiToivio** [comment]
Yhdistin ne: https://www.transifex.com/projects/p/froide/language/fi_FI/

Nyt on vaan paha sanoa ottaako se oikeasti uusimman ja parhaimman käännöksen.

**Comment by jaakkokorhonen** [comment]
On vaan yks tapa tietää varmasti :)

**Comment by jaakkokorhonen** [comment]
Etusivun  Lue lisää konseptista! -linkki viittaa osoitteeseen http://tietopyynto.fi/apua/, ja footerin http://tietopyynto.fi/apua/Tietoja%20palvelusta/ antaa sekin 404.

Sisältödokkarit voisi kirjoittaa tänne: https://tietopyynto.hackpad.com/collection/uqaT0RpQ22P
