### ISSUE TITLE
500 kun yritän asettaa tietopyynnön tilan

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#20]
antaa 500 kun yritän asettaa tietopyynnön tilan. Lähetys ja uudelleenvastaus toimii ok.

**Comment by TomiToivio** [comment]
Se vaati laittamaan "kustannukset" päälle ettei bugaa. En tiedä voiko suomalaisessa tietopyynnössä edes olla "kustannuksia"?

**Comment by jaakkokorhonen** [comment]
joo voihan siinä olla vaikka 1 tms, laskuriarvo.
