### ISSUE TITLE
Aseta kuvituskuva etusivulle

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#21]
kuvituskuva etusivulle https://drive.google.com/file/d/0B5Li3-76N_5oUmttVWZJcTh2QVE/edit?usp=sharing

Jos pitää olla joku tietty reso niin kerro, ja muokaan.

**Comment by TomiToivio** [comment]
Siellä, mutta enpä tiedä sopiiko se niin hyvin: http://tietopyynto.fi/

**Comment by apoikola** [comment]
nyt ei näytä urli pelittävän. Osallistamis-mielessä tämä voisi olla sellainen, mihin pyytäisi beta-testauksen aikana ehdotuksia laajemmaltakin porukalta tyyliin " nyt kuvituskuvana tämä, mutta olisiko jollain parempia ehdotuksia"
