### ISSUE TITLE
Update Open Data API instruction page to front page / footer

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#22]
http://froide.readthedocs.org/en/latest/api/

**Comment by TomiToivio** [comment]
Tähän tyyliin toimii kyllä: http://tietopyynto.fi/api/v1/request/search/?format=json&q=oikeus

**Comment by TomiToivio** [comment]
Ja viranomaisten haku: http://tietopyynto.fi/api/v1/publicbody/search/?format=json&q=oikeus

**Comment by jaakkokorhonen** [comment]
ah noni

**Comment by TomiToivio** [comment]
APIn dokumentaatio on muuten tuolla, enpä tiedä onko tällaista matskua tarpeen suomentaa: http://tietopyynto.fi/api/v1/docs/

**Comment by TomiToivio** [comment]
Nykyisen APIn kehitys ei jatku: https://github.com/stefanw/froide/issues/136

![creating new request through the api issue 136 stefanw froide](https://cloud.githubusercontent.com/assets/1176369/5673009/609d1f7a-979f-11e4-9bbe-c7caf49cf92c.png)

Varmaan tälle ei juuri nyt kannata tehdä mitään.

**Comment by jaakkokorhonen** [comment]
Nii linkki vaan footeriin. Ja vaikka linkki tohon. Sisältödokkari siis.

**Comment by jaakkokorhonen** [comment]
pitää olla mainittuna footerissa niin että käyttäjille tulee mieleen käyttää sitä

**Comment by TomiToivio** [comment]
Eiks tää virallinen dokumentaatio riitä: http://tietopyynto.fi/api/v1/docs/
