### ISSUE TITLE
WRITE Tietoja palvelusta

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#23]

**Comment by TomiToivio** [comment]
http://tietopyynto.fi/apua/Tietoja%20palvelusta/

**Comment by apoikola** [comment]
Tekstien muokkaus olisi varmaankin helpointa gdocsissa, tein sitä varten nyt tyhjän dokkarin, kopsikaahan pohjat sinne, niin voin tarttua toimeen https://docs.google.com/document/d/1Ko7g1NqeXUqg7FYwJVOvNGPLSAWVo1mNVe0uDPSDDCY/edit?usp=sharing

**Comment by jaakkokorhonen** [comment]
Sisältödokkarit voisi kirjoittaa tänne: https://tietopyynto.hackpad.com/collection/uqaT0RpQ22P
