### ISSUE TITLE
WRITE Käyttöehdot

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#25]

**Comment by TomiToivio** [comment]
http://tietopyynto.fi/apua/tietopyyntojen-teko/

**Comment by apoikola** [comment]
urli ei tässäkään pelitä, mutta Jyväskylän yliopiston kanssa on sovittu, etteä he voivat olla sisällöntuottajina saitille. Täällä on paljon hyvää asiaa, josta relevantin osan voisi siirtää / kopioida tietopyyntöön -> http://www.julkisuuslaki.fi/

**Comment by jaakkokorhonen** [comment]
@apoikola kopipasteiletko olennaisimman tuolta julkisuuslaki.fi -sivulta vaikka tähän taskiin niin, me julkaistaan se sivustolla, saadaan tämä sisältödokumettitehtävä pois alta.

**Comment by apoikola** [comment]
työstän staattiset tekstit tänne http://okf.fi/tietopyynto-staattiset helpompi kommentoida ja editoida, kuin täällä issuessa.

**Comment by TomiToivio** [comment]
Näiden sisältö taitaa puuttua vieläkin.

**Comment by jaakkokorhonen** [comment]
Rekisteriseloste on http://tietopyynto.fi/apua/yksityisyyden%20suoja/
Käyttöehdot puuttuu http://okf.fi/tietopyynto-staattiset -sivulta. Ping @apoikola @joonasp.

**Comment by jaakkokorhonen** [comment]
Sisältödokkarit voisi kirjoittaa tänne: https://tietopyynto.hackpad.com/collection/uqaT0RpQ22P

**Comment by jaakkokorhonen** [comment]
Liittyy #47
