### ISSUE TITLE
WRITE Tietosuojakäytännöt

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#26]

**Comment by TomiToivio** [comment]
http://tietopyynto.fi/apua/sinun-yksityisyytesi/

**Comment by opottone** [comment]
Usein viranomaisilta pyydetyissä asiakirjoissa on henkilötietoja. Miten varmistetaan, että niiden julkaiseminen internetissä on asiallista ja henkilötietolain rajoissa sallittua?

**Comment by opottone** [comment]
Ehkä olen turhan pessimistinen, mutta pelkään että tästä tulee vielä ongelmia. Kun henkilötietolain takia viranomaisetkaan eivät saa pitää julkisia asiakirjoja internetissä, miksi me saisimme?

**Comment by jaakkokorhonen** [comment]
Kuka on käyttänyt tietopyyntöpalvelua tietää, että 
käyttäjää kehotetaan mustaamaan vastauksista henkilötiedot 
ennen julkaisua.
Tietosuojakäytännöt koskee siis järjestelmän tunnusten käsittelyä ja sisältää tietojen pyytäjälle muistuksen pitää oma nimi vain otsikkotiedoissa, joista järjestelmä sen automaattisesti poistaa.

**Comment by jaakkokorhonen** [comment]
#53 täytetty, pitää vielä julkaista.
