### ISSUE TITLE
How to implement several countries?

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#28]

**Comment by jaakkokorhonen** [comment]
Needs to be planned with @stefanw

**Comment by stefanw** [comment]
Froide supports multiple jurisdictions and multiple laws per jurisdiction. Not sure if this already fits your use case though.

**Comment by jaakkokorhonen** [comment]
The use case would be that we have Norway, Denmark, Iceland, Sweden Finland and Estonia that would need to have FOI solution but will have a bit separate data. On that note, have you @stefanw considered EU FOI requests?

**Comment by stefanw** [comment]
There is asktheeu.org for EU FOI requests.

**Comment by TomiToivio** [comment]
We would need different domains for different languages? Now all tietopyynto.fi email goes into the same mailbox, which also means all kinds of sysadmin spam ends up in deferred messages.

**Comment by apoikola** [comment]
I see here two possible paths:

A: Cloud service FOI -site (FROIDE Software as a Service)
- any jurisdiction could set up own site that runs in the same cloud installation
- needs further development efforts

B: Separate installations for each jurisdiction (FROIDE SERVER Infrastructure as a Service)
- easy to setup (Docker?) installations for different countries, these could be hosted in centralized manner in the same server.
- closer to current path, could be tested in the Nordics, in the long run more work in maintenance

**Comment by stefanw** [comment]
I doubt that a central instance will be able to cover all the needs of country-specific platforms.
I also see that you forked Froide which is not the best way to run a Froide instance. The recommended way is to have a separate Django project with Froide as a Django app dependency. An example is this repository: https://github.com/okfn/froide-theme

This theme approach allows you to customise the looks and additional URLs while not modifying froide directly.

**Comment by jaakkokorhonen** [comment]
Great, we will look into theme approach. This sounds spot-on what we need. Thanks @stefanw !
