### ISSUE TITLE
Käännös suomeksi

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#3]
django.po pitäisi suomentaa https://github.com/okffi/froide/blob/master/locale/en/LC_MESSAGES/django.po

Ei ole kovin iso, mutta laitoin nyt samalla kyselyä, että saisiko Froiden okfn:n Transifex-projektiksi.

https://github.com/stefanw/froide/issues/95

https://twitter.com/apoikola/status/399147860509220866

Edit: löysin Transifex -projektin https://www.transifex.com/projects/p/froide/

**Comment by apoikola** [comment]
Stepit:
1. Raakakäännetään loputkin stringit kertaalleen Githubiin https://github.com/okffi/froide/blob/master/locale/fi/LC_MESSAGES/django.po
2. Laitetaan raakakäännetty .po Transifexiin https://www.transifex.com/projects/p/froide/
3. Laitetaan raakakäännetty versio näkösälle http://froide.inssipilvi.info/
4. Pyydetään ihmisiä testikäyttämään palvelua ja etsimään huonoja syomennoksia ja tekemään parannukset Transifexin kautta
5. Jäädytetään tuotantpkäyttöön menevä suomennosversio

**Comment by apoikola** [comment]
vaihe 1. eli raakasuomennos on nyt valmis (en ainakaan serchillä löytänyt enää kääntämättömiä stringejä), oisko @katis saumaa kokeilla, saisiko tuon demoversion pyörimään uudelleen nyt?

https://github.com/okffi/froide/blob/master/locale/fi/LC_MESSAGES/django.po

Hmm.. vaikuttaa, että vieläkin n jokunen syntaksi fiba mukana. Minulla ei ole pythonia ja compilemessagesia asennettuna, joten en pysty tehokkaasti etsimään virheitä.

**Comment by apoikola** [comment]
Vaihe 2. valmis tiedosto suostui nyt menemään Transifexiin https://www.transifex.com/projects/p/froide-fi/language/fi/

nyt tarttis saada vain palvelu pyörimään, jotta voisi testata käännösten mielekkyyttä ja Transifexin review -toiminnolla kattoa läpi ja parannella.

**Comment by pe3** [comment]
OKFFI:n hostausta odotellessa kantsii varmaan tsekkailla Digital Oceanin 5$/kk hostaus https://www.digitalocean.com

**Comment by apoikola** [comment]
kirjauduin sisään, siellä oli taas se toisaalla puhuttu Docker vaihtoehtona, oletko itse kokeillut? Vaihtoehtona myös eri linux distroja. Mitä suosittelet?

Käännöksiin liittyen Rufus perusti nyt Froiden okfn:n tilin alle, katsotaan, miten elämä etenee https://www.transifex.com/projects/p/froide-2/language/fi/

Yritin myös tehdä pull requestia, mutta jokin asia mättää, Froiden continuous integration -systeemi ei buildannut sitä :/ https://github.com/stefanw/froide/pull/97

**Comment by katis** [comment]
Oma palvelin on Digital Oceanilla, toiminut oikein mainiosti.
Backupeista joutuu tulevaisuudessa maksamaan vähän ylimääräistä:

```
Please note: We will begin charging for automated backups starting on
July 1st, 2013. You will receive your first bill for enabled backups on
August 1st, 2013. Pricing is set at 20% of the Droplet's monthly cost
(e.g. It will cost $1/mo. to enable backups for a 512MB Droplet)"
```

Ubuntu LTS on suht kätevä valinta distrolle, mutta en usko että sillä hirveästi on väliä, kunhan MySQL/Postgres ja Pythonin löytyy paketinhallinnasta.

Ehdin viikonloppuna säätämään tuon esimerkkiasennuksen kanssa.

**Comment by apoikola** [comment]
Translations into Finnish and Swedish are almost done in https://www.transifex.com/projects/p/froide/
