### ISSUE TITLE
DESIGN automated weekly FOI request

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#30]
Puhemiesneuvoston pöytäkirjat julkaistaan nykyään vain eduskunnan intrassa. Jos sinne pistäisi automaattisen tietopyynnön vaikka kerran viikossa (tai aina kokouksen jälkeen, jos tieto löytyy jostain ja saa scrapetettua), niin pöytäkirjat voisi julkaista kaikki avoimesti.

**Comment by TomiToivio** [comment]
Froide actually has a scraper already: https://github.com/stefanw/froide-foiidea

@stefanw can we test Froide FOI Idea generator already?

**Comment by stefanw** [comment]
froide-foiidea uses feeds of news sites and tries to find opportunities for FOI requests. Very simple and crude and I'm not using it in production anymore. But you can definitely try it out!

**Comment by TomiToivio** [comment]
Yeah, now it fetches the RSS feed of the Ministry of Justice.

**Comment by TomiToivio** [comment]
Seems like you cannot create a new request through the API: http://tietopyynto.fi/api/v1/docs/

**Comment by TomiToivio** [comment]
Made a script for this since you cannot use the API. 

How will we exactly use this? Send a weekly FOI request to the Parliament? 

What kind of contents should it have?

**Comment by apoikola** [comment]
this could be piloted manually first.

**Comment by jaakkokorhonen** [comment]
Yes well now we need a real-life problem that is sensible for testing this. 20-50 emails to similar organisations by the end of the year. One cool thing would be journal numbers for new procurements in some few selected cities' archiving systems systems.

**Comment by jaakkokorhonen** [comment]
Yes that's just suitable. We already have a manual test: http://tietopyynto.fi/r/88

**Comment by jaakkokorhonen** [comment]
That could be run for major cities, like quarterly. You get some data from Hilma, but it does not show all. This could even be used to refactor and enrich Hilma data.

**Comment by TomiToivio** [comment]
I have a script for this. Now the question is what kind of FOI requests it should send, to whom, and how often?

**Comment by jaakkokorhonen** [comment]
Sweet. Procurement update for municipalities -or any organisation - is sincerely a serious thing to have. http://tietopyynto.fi/r/88

**Comment by TomiToivio** [comment]
I think we just need a list of FOI requests that should be sent as a cron job... 

1) When will cron send it 
2) Which public body it will be sent to
3) Contents of FOI request text

**Comment by TomiToivio** [comment]
Tähän on tosiaan ollut skripti jo jonkin aikaa, jos vaan tietäisi millaisia tietopyyntöjä lähetetään, milloin ja kenelle.

**Comment by apoikola** [comment]
olennaista mun mielestä, että tietopyynnön tuloksia myös hyödynnetään, ettei vaan tykitetä pyyntöjä sen takia, koska se on mahdollista. Ketjun avaus oli eduskunnan puhemiesneuvoston pöyätäkirjoista - lähestyisin sitä:
1. yksittäinen tietopyyntö (ellei ole jo tehty)
2. katsotaan, mitä mielenkiintoista niissä pöytäkirjoissa on
3. jos halutaan auki pyydetään Eduskuntaa julkaisemaan sivuillaan säännöllisesti ja sanotaan, että muussa tapauksessa joudumme pyytämään säännöllisesti tietopyynnöllä

Näin skripti itseasiassa toimii parhaiten silloin, kun sitä ei edes tarvitse käyttää.

**Comment by jaakkokorhonen** [comment]
Unohda @apoikola puhemiesneuvosto sille ei juuri nyt ole kiinnostunutta lukijaa.

Konkreettinen hyödyllinen case oli hankintapäätökset niiltä organisaatioilta jotka ei ole avanneet hankintotojaan esim hare.vn.fi ja hilman kaltaisista järjestelmistä avoimena datana. Näitä pyydetään koska hankinnnoista on runsaasti julkista keskustelua, joka voisi olla faktapohjaisempaakin. Tämä liittyy myös siihen kohta ajankohtaiseen tilanteeseen kun uudella halituskaudella jengi innostuu ostelemaan juttuja uusilla budjeteilla.

**Comment by jaakkokorhonen** [comment]
Toinen mikä tulee myöhemmin on hakkuuseuranta metsäkeskuksille ja suojelualueiden hakkuulupaseuranta ELY-keskuksille.

**Comment by TomiToivio** [comment]
Onko näihin tietopyyntöihin tarkempaa sisältöä?

**Comment by jaakkokorhonen** [comment]
Täs toinen http://tietopyynto.fi/r/141

**Comment by TomiToivio** [comment]
Uskaltaakos automatisoidun tietopyynnön nyt laittaa pyörimään? :)

**Comment by TomiToivio** [comment]
Sitä ei tosiaan voi tehdä oikeaoppisesti APIn kautta: https://github.com/stefanw/froide/issues/136

**Comment by TomiToivio** [comment]
Ensi kuun ensimmäisenä päivänä lähtee eka automatisoitu tietopyyntö.

**Comment by apoikola** [comment]
lähteekö automatisoidutkin pyynnöt kuitenkin jonkun henkilön nimissä, eli
kuka on kirjeenvaihdossa se tietopyynnön lähettäjä, jonka kanssa pyyntöön
vastaava virkamies keskustelee? Sorry, jos kysymys oli tyhmä ja vastaus
selviää jostain, mistä en osannut sitä etsiä.

On Wed, Jan 28, 2015 at 11:36 AM, Tomi Toivio notifications@github.com
wrote:

> Ensi kuun ensimmäisenä päivänä lähtee eka automatisoitu tietopyyntö.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/30#issuecomment-71805486.

## 

+358 44 337 5439
about.me/apoikola

**Comment by TomiToivio** [comment]
Joo, pakkohan niillä on olla lähettäjä.

**Comment by TomiToivio** [comment]
Lisäksi niitä ei tosiaan voi tehdä APIn kautta, joten IMHO skriptiä ei kannata julkaista.

**Comment by jaakkokorhonen** [comment]
laitetaan privarepo

**Comment by jaakkokorhonen** [comment]
tänne https://github.com/okffi/froide-customisations

**Comment by TomiToivio** [comment]
Sinne meni.
