### ISSUE TITLE
Libreoffice PDF-tiedostoja varten

### ISSUE THREAD

**Issue by TomiToivio** [okffi/tietopyynto#31]
PDF-tiedostoja kyllä pääsee sensuroimaan, mutta näyttäisi kuitenkin jämähtävän kun yrittää julkaista sutatut versiot.

**Comment by TomiToivio** [comment]
Pitäisi muuten tarkastaa ettei Froiden sensuurissa käy näin, tosin se toimii LibreOfficella: http://www.hs.fi/kaupunki/a1415073742718

**Comment by jaakkokorhonen** [comment]
ei, tulee bittikarttana froidesta.
