### ISSUE TITLE
Viranomaisten hyväksyminen

### ISSUE THREAD

**Issue by TomiToivio** [okffi/tietopyynto#33]
Tietopyyntöjä pitäisi myös käydä hyväksymässä.

Nyt joukko tietopyyntöjä jäi "Odotetaan viranomaisen vahvistusta"-tilaan:

http://tietopyynto.fi/tietopyynto/tilastoskeskuksen-vakiotuotteiden-ja-tietokantapalvelujen-kulut-per-maksava-asiakas/
http://tietopyynto.fi/tietopyynto/tilastokeskuksen-yksityisen-sektorin-asiakkaiden-vakiotuotteiden-ja-tietokantapalvelujen-korvaukset/
http://tietopyynto.fi/tietopyynto/tilastoskeskuksen-vakiotuotteiden-ja-tietokantapalvelujen-kulut/

Eli tässä tapauksessa jonkun pitäisi hyväksyä käyttäjän luoma Tilastokeskus-viranomainen, että tietopyynnöt menisivät eteenpäin.

Eli jonkinlaista aktiivista moderaatiota tarvittaisiin sisältöpuolelle.

**Comment by apoikola** [comment]
Lähtevätkö nämä eteenpäin oikeasti, vai onko meneillään hiljainen testiperiodi? Voin tulla moderointirinkiin, kun vain kerrotaan, että mitä pitää tehdä - aloitin nyt siitä, että loggasin sisään github-tunnareilla.

**Comment by TomiToivio** [comment]
Kokeile mennä adminiin: http://tietopyynto.fi/admin/

**Comment by TomiToivio** [comment]
Voi olla että joudut vaihtamaan salasanan ennen kuin pääset adminiin: http://tietopyynto.fi/tili/settings/

(Python Social Auth ei päästä loggaamaan salasanalla ennen kuin se on vaihdettu, joten jos teit käyttäjätunnuksen Githubin kautta et pääse sisään salasanalla ennen sen vaihtamista...)

**Comment by TomiToivio** [comment]
Lisäksi Django menee sekaisin jos on jo viranomainen "tilastokeskus" ja joku ehdottaa uutta viranomaista "tilastokeskus"... 

http://tietopyynto.fi/admin/publicbody/publicbody/?q=tilastokeskus

**Comment by apoikola** [comment]
pääsin adminiin, mutta ehdotetuissa viranomaisissa ei ainakaan ollut mitään.

**Comment by TomiToivio** [comment]
Viranomaiset siis tuolla: http://tietopyynto.fi/admin/publicbody/publicbody/

Ehdotetut viranomaiset on kun joku jättää tietopyynnön ilman viranomaista ja joku muu ehdottaa sopivaa viranomaista...

**Comment by apoikola** [comment]
ok menin Tilastokeskuksen kohtaan ja poistin tagin "tarkastamatta" (oliko tämä se, mitä piti tehdä) - sen jälkeen tuli:
![screen shot 2014-09-22 at 19 40 34](https://cloud.githubusercontent.com/assets/143108/4359968/3b595d8c-4277-11e4-9b64-b7420c3abc8d.png) urlista http://tietopyynto.fi/viranomainen/tilastokeskus/

**Comment by TomiToivio** [comment]
Käyttäjän laittaman viranomaisen admin-sivulle siis tulee sellainen "Hyväksy viranomainen"-nappi, jota pitää painaa ennen kuin se lähettää tietopyynnön sähköpostilla.

Tageilla ei ole mitään tekemistä tarkastamisen kanssa. Se "tarkastamatta"-tagi on siellä vain muistutuksena ettei niitä kaikkia ole katsottu käsin.

**Comment by TomiToivio** [comment]
Koska skriptaamalla sai kaavittua kunnolla vain kunnat on kaikissa muissa tarkastamatta-tagi ja kunnissa kunta-tagi. :)

**Comment by TomiToivio** [comment]
Olikohan Tilastokeskus muuten tuplana, koska: https://github.com/okffi/tietopyynto/issues/36

Tosiaan jonkun pitäisi ilmeisesti aktiivisesti käydä hyväksymässä viranomaisia ja poistamassa tuplaviranomaisia. Ei tämä taida toimia ilman että joku ylläpitää käsin.

**Comment by TomiToivio** [comment]
Poistin äsken ison kasan tuplaviranomaisia ja hyväksyin käyttäjien viranomaisia, joten kasa tietopyyntöjä lähti vasta nyt.

**Comment by jaakkokorhonen** [comment]
Onko @TomiToivio edelleen niin että Käyttäjän laittaman viranomaisen admin-sivulle siis tulee sellainen "Hyväksy viranomainen"-nappi, jota pitää painaa ennen kuin se lähettää tietopyynnön sähköpostilla? 

Meneekö näistä notifikaatioit sähköpostilla jonnekin? Saako menemään? Tai vielä parempi, niin että viranomainen luodaan lennosta?

**Comment by TomiToivio** [comment]
Tulee "Hyväksy viranomainen"-nappi.

Mutta sillä ei varmaan ole paljonkaan väliä enää, kun tärkeimmät viranomaiset on jo valmiina tietokannassa.
