### ISSUE TITLE
Itseänihenkilökohtaisesti koskeva pyyntö (tee-tietopyynto) sivulle linkin korjaus

### ISSUE THREAD

**Issue by markosu** [okffi/tietopyynto#35]
Tee tietopyyntö sivulle http://tietopyynto.fi/tee-tietopyynto/  voisi vaihtaa 115.de osoitteen tilalle http://www.kansalaisneuvonta.fi/

![henkilokohtainen_pyynto](https://cloud.githubusercontent.com/assets/6770959/4505155/3f44f178-4af0-11e4-814e-8fceb2e5f780.PNG)

**Comment by apoikola** [comment]
Kiitos muutin tämän nyt käännöstiedostoon https://www.transifex.com/projects/p/froide-2/language/fi/ (vapaaehtoiset käännösten parantajat tervetulleita). Tulee sivulle sitten, kun asennetaan uudet käännökset paikalleen, sitä ennen pitänee vähän muutakin kielenhuoltoa tehdä.
