### ISSUE TITLE
UPDATE governament body contact info list

### ISSUE THREAD

**Issue by TomiToivio** [okffi/tietopyynto#36]
Jos sama viranomainen on tuplana Froide antaa virheilmoituksen, kun sama url palauttaa kaksi viranomaista (esim. http://tietopyynto.fi/viranomainen/sisaministerio/ oli äsken tuplana).

En tiedä onko tämän estämiseen mitään tapaa, jos käyttäjien annetaan tehdä viranomaisia. Jonkun pitää vaan poistella tuplat käsin. 

Traceback (most recent call last):

  File "/home/django/tietopyynto/pyenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)

  File "/home/django/tietopyynto/froide/froide/publicbody/views.py", line 84, in show_publicbody
    obj = get_object_or_404(PublicBody, slug=slug)

  File "/home/django/tietopyynto/pyenv/lib/python2.7/site-packages/django/shortcuts/**init**.py", line 113, in get_object_or_404
    return queryset.get(_args, *_kwargs)

  File "/home/django/tietopyynto/pyenv/lib/python2.7/site-packages/django/db/models/query.py", line 313, in get
    (self.model._meta.object_name, num))

MultipleObjectsReturned: get() returned more than one PublicBody -- it returned 2!

**Comment by TomiToivio** [comment]
Nytpä Oikeusministeriötä on kaksi kappaletta, koska molemmille oli jo tietopyyntöjä: 

http://tietopyynto.fi/viranomainen/oikeusministerio/
http://tietopyynto.fi/viranomainen/oikeusministerio2/

En nyt jaksanut ruveta yhdistämään niitä. 

Mitähän tälle tekisi?

**Comment by TomiToivio** [comment]
Itse asiassa tuplia oli aika paljon. Poistelin niitä ja hyväksyin viranomaisia. 

Tämä ei taida toimia ilman aktiivista administraatiota.

**Comment by TomiToivio** [comment]
Pitäisköhän poistaa kylmästi kaikki kaavitut viranomaiset, joilla ei ole sähköpostiosoitetta. Nehän eivät edes näy käyttäjille, jolloin kaikki näemmä tekevät saman viranomaisen uudelleen, jolloin Froide bugaa tuplaviranomaiseen. 

Tosin käyttäjän tekemä viranomainen pitäisi silti käydä hyväksymässä käsin.

**Comment by apoikola** [comment]
sorry, että en ole ollut ihan hereillä tämän pilotoinnin alussa (en tajunnut, että nyt on jo lähtenytihan oikeita tietopyyntöjä). Mun mielestä järkevää olisi:
1. vetää viranomaislista gdocsiin, pitää tunnin joukkoistamissessio, jossa viisi aktiivista kaivaa meiliosoitteita puuttuville viranomaisille. (olin henkisesti varautunut, että kunhan aika koittaa, niin voin tällaisen session järkätä)
2. Niille, joille ei ehditä ekassa sessiossa löytämään oikeaa osoitetta laitettaisiin osoitteeksi joku pseudo-osoite (esi. osite.puuttuu@okf.fi), jotta ne tulisivat Froidessa näkyviin ja ihminen, joka oikeasti haluaa lähettää tällaiselle tietopyynnön, niin voi sitten etsiä siinä vaiheessa oikean osoitteen ja päivittää sen sinne.
3. Ajaa tämä (ja vain tämä) kantaan.

## 

Jos tuo 1-2-3 on nyt mahdotonta tai hankalaa tehdä, kun on jo oikeita tietopyyntöjä, niin sitten pitää keksiä jotain muuta. Mitä tuumaa @jaakkokorhonen

**Comment by jaakkokorhonen** [comment]
Kun katsoo dataa http://tietopyynto.fi/admin/publicbody/publicbody/, voi todeta että on ylipäätään aika kiva juttu että viranomaisen olemassaolo on tunnistettu. Kokonaisuuden kannalta tehokkainta hyödyntää nyt tuo data ja pitää joukkoistamissessio homman viimeistelemiseksi.

**Comment by TomiToivio** [comment]
Käyttäjille ei kuitenkaan näy ollenkaan niitä viranomaisia, joilla ei ole sähköpostiosoitetta, joten kaikki näköjään luovat vaan saman viranomaisen uudestaan tietopyyntöä tehdessään.

**Comment by TomiToivio** [comment]
Tosin joissain tapauksissa luovat vaikka viranomainen olisi olemassa, joten oikeusministeriötä on nyt kaksi kappaletta, kun molemmille oli jo tietopyyntöjä: 

http://tietopyynto.fi/viranomainen/oikeusministerio/
http://tietopyynto.fi/viranomainen/oikeusministerio2/

Tosiaan Froide kaatuu jos samalla urlilla tulee kaksi viranomaista. 

Ilmeisesti alkuperäisessä saksankielisessä versiossa käyttäjien ei anneta tehdä itse viranomaisia, joten homma hieman bugaa.

**Comment by jaakkokorhonen** [comment]
Niin ne pitää hillota spreadsheettiin, korjata ja syöttää takas. @apoikola hoitaa ku ehtii.

**Comment by apoikola** [comment]
"Käyttäjille ei kuitenkaan näy ollenkaan niitä viranomaisia, joilla ei ole sähköpostiosoitetta, joten kaikki näköjään luovat vaan saman viranomaisen uudestaan tietopyyntöä tehdessään."

-> voiko nyt väliaikaisesti laittaa osoitteeksi jonkun pseudo-osoitteen, kuten esim. osite.puuttuu@okf.fi, jotta ne tulisivat Froidessa näkyviin, eikä tuplia luoda nyt.

Mielelläni hoidan joukkoistamista tietojen keruuseen, jos voitte purskauttaa Froidesta ulos johonkin tiedostoon sen datan, mitä nyt on ja kuittaatte, että kun joukkoistaminen on tehty, niin täydennettyjen tietojen takaisin viemiseen on olemassa (ei manuaalinen) keino.

Mikäli takaisinvienti ei onnaa ilman koko kannan jyräämistä, niin pitää ihmetellä, voisiko joukkoistamisen tehdä Froiden käyttiksen kautta.

**Comment by TomiToivio** [comment]
Tämä taitaa jo olla menneisyyttä.
