### ISSUE TITLE
UPDATE logo

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#37]
![screenshot 2014-10-09 12 41 39](https://cloud.githubusercontent.com/assets/3482497/4574036/c6a8a09a-4f98-11e4-98f7-5f685240b04a.png)

**Comment by apoikola** [comment]
![logo-okf-finland](https://cloud.githubusercontent.com/assets/143108/4582973/99a0249c-4fed-11e4-8926-c80a51597011.jpg)

**Comment by jaakkokorhonen** [comment]
a new image file needs to be done
