### ISSUE TITLE
DESIGN layout for buttons

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#40]
![screenshot 2014-10-09 12 39 29](https://cloud.githubusercontent.com/assets/3482497/4574178/3d0294c0-4f9a-11e4-8340-5398fb46a52d.png)
Buttons are hard to recognize.
Buttons could be in the bottom rather than on the side.

**Comment by haphut** [comment]
Colors changed. Tomi and I did not see a reason to reorder the buttons.
