### ISSUE TITLE
Clean up fonts preferences

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#42]
![screenshot 2014-10-09 12 37 06](https://cloud.githubusercontent.com/assets/3482497/4574269/f9ea7dc8-4f9a-11e4-9f6e-94272501f52c.png)
Set up fonts so that there is only 3-4 sizes/styles/font settings instead of 9-10 like in here.

**Comment by miskaknapek** [comment]
yeps, good plan to minimise the fonts. 
I'll have a closer look at it. 
using Open Sans might be a good start. it's even openly licensed :) ( though commissioned by Google… ) http://en.wikipedia.org/wiki/Open_Sans

Here's an ultra quick test - not too hip and not too serious ;) - 
![screen shot 2014-10-18 at 16 39 35](https://cloud.githubusercontent.com/assets/1816501/4689801/4b4ef76a-56cc-11e4-9e4f-bc4b27b204e5.png)

**Comment by jaakkokorhonen** [comment]
@TomiToivio can you install Open Sans, just to see how it is technically feasible.

**Comment by jaakkokorhonen** [comment]
We'll update css in a next phase.

**Comment by jaakkokorhonen** [comment]
@miskaknapek  #29 describes css to import different font.

**Comment by TomiToivio** [comment]
Now it is Open Sans.

**Comment by jaakkokorhonen** [comment]
Looks good
