### ISSUE TITLE
Pätevämpi tekstiosuus asiakirjapyyntöön

### ISSUE THREAD

**Issue by kyyberi** [okffi/tietopyynto#44]
Tuli tietooni eräältä paljon näitä tietopyyntöjä käsittelevältä viranomaiselta että alla oleva tekstimuotoilu lomakepohjassa olisi oikeampi:

"Viitaten viranomaisen toiminnan julkisuudesta annetun lain (621/1999) 13 pykälään pyydän seuraavat asiakirjat sähköisesti tähän sähköpostiini. Mikäli asiakirjat eivät ole julkisia pyydän ne sähköisinä julkisilta osiltaan. Mikäli asiakirjapyynnöstäni kieltäydytään edes osin pyydän saada asiassani valituskelpoisen hallintopäätöksen valitusosoituksineen. Tietopyyntöni käsittelyssä pyydän noudattamaan julkisuuslain määräaikaa."

Tähän alle pitäisi sitten käyttäjä listaa diaarinumerot joiden asiakirjat halutaaan.

**Comment by apoikola** [comment]
Joo tämä on varmasti hyvä. Jos oikein muistan, niin viittaus lakiin taitaa tulla meili templateissa loppuun ja pyydetyt asiakirjat ennen sitä. Diaarinumeroiden olemassaolo tai se, että pyytäjä ne tietäisi ei ole edellytys tietopyynnön tekemiseslle - toki sellaiset kannattaa laittaa, jos ovat tiedossa, niin nopeuttavat toimintaa.

laittaako @jaakkokorhonen minulla ei taida olla adminoikeuksia.

**Comment by jaakkokorhonen** [comment]
Kielitekstit menee Transifexiin: https://www.transifex.com/projects/p/froide/translate/#fi_FI/froide/19676994

Admin-tunnarit Jogilla jo näyttää olevan: http://tietopyynto.fi/admin/

**Comment by jaakkokorhonen** [comment]
Minä en ehkä pyytäisi noudattamaan julkisuuslain määräaikaa, olisihan mukavaa että viestiin vastataan heti. Määräajasta on muistutusviesti mikä lähtee siellä kahden viikon tietämillä jos normaali virkamiesetiikka ei ole saanut virkamiestä vastaamaan.

**Comment by TomiToivio** [comment]
Noita tekstejä voi muuttaa täältä: http://tietopyynto.fi/admin/publicbody/foilaw/1/

(Ei tule Transifexistä...)

**Comment by jaakkokorhonen** [comment]
Muutetaan pliis transifexiin ja sieltä hallitusti.

**Comment by TomiToivio** [comment]
Ei noita tekstejä taida edes olla Transifexissä, kun ne on tarkoitus kirjoittaa erikseen jokaiselle "julkisuuslaille".

Eli "julkisuuslakeja" olisi vähintään kaksi, Suomen julkisuuslaki ja Ahvenanmaalle joku oma versionsa?

**Comment by opottone** [comment]
Lieneeköhän tuo tekstimuotoilu parempi. Lakihan ei mitään muotovaatimuksia sisällä. Julkisuuslain tunteminen ja julkisuusperiaatteen noudattaminen kuuluvat virkamiehen virkavelvollisuuksiin ilmankin kansalaiselta saatua opastusta.

Tai jos esitetään tarkempia vaatimuksia niin vaaditaan sitten tiedon antamista mahdollisimman pian, mitä lakikin edellyttää, eikä vain lain sallimien maksimiaikojen puitteissa.

Myös tuo valituskelpoisen päätöksen pyytäminen vähän epäilyttää. Ensimmäinen askelhan ennen (korkeimpaan) hallinto-oikeuteen valittamista on asian saattaminen viranomaisen ratkaistavaksi (julkisuuslaki 14 § 3 mom). Onko tarkoituksenmukaista (tai edes mahdollista) automaattisesti ennakkoon saattaa asia viranomaisen ratkaistavaksi?

**Comment by apoikola** [comment]
Valituskelpoista päätöstä yleensä kannattaa pyytä, jos viranomainen vastaa kieltävästi. Tämä on kokeneilla tietopyynnön tekijöillä, kuten journalisteilla tiedossa, mutta tämän palvelun kautta uudetkin ihmiset tekevät pyyntöjä ja ilman opastusta he eivät ehkä hoksaa pyytää valituskelpoista päätöstä.

Valituskelpoinen päätös on käytännössä se viranomaisen ratkaisu, jossa kirjallisesti perustellaan, miksi pyyntö ei ole sellainen, johon suostutaan.

**Comment by opottone** [comment]
Virkamiehen kieltävään päätökseen ei haeta muutosta valituksella vaan saattamalla asia viranomaisen ratkaistavaksi (julkisuuslaki 14 § 3 mom), joten valitusosoitteesta puhuminen on vähän hämäävää.

**Comment by apoikola** [comment]
joo valitusosoite on hallinto-oikeus no question about that

**Comment by opottone** [comment]
Siispä sitä päätöstä valitusosoitteineen on turha heti aluksi pyytää kun sitä ei voi saada.

**Comment by apoikola** [comment]
näkisin, että yleensä prosessi:
1) tietopyyntö
2) jos kieltävä vastaus, niin pyydetään valituskelpoiista päätöstä (=asia
viranomaisen ratkaistavaksi)

nyt vain on yhdistetty 1 ja 2 samaan tekstiin ehdollisena, koska muuten
tietopyyntö.fi http://xn--tietopyynt-ncb.fi käyttäjät eivät välttämättä
ymmärtäisi tehdä vaihetta 2 lainkaan.

Valitusosoitteen pyytäminen on tosiaan turhaa.

-Jogi

2014-10-31 10:00 GMT+02:00 opottone notifications@github.com:

> Siispä sitä päätöstä valitusosoitteineen on turha heti aluksi pyytää kun
> sitä ei voi saada.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/44#issuecomment-61229393.

## 

+358 44 337 5439
about.me/apoikola

**Comment by jaakkokorhonen** [comment]
Oliko joku tietopyyntö missä olisi ilmennyt tarve muutoksiin. Mikä on tavoiteltu hyöty?

**Comment by apoikola** [comment]
Onhan se ihan relevantti muutostarve, jos paljon tietopyyntöjä käsittelevä
viranomainen on vaivautunut antamaan palautetta :)

2014-10-31 14:46 GMT+02:00 Jaakko Korhonen notifications@github.com:

> Oliko joku tietopyyntö missä olisi ilmennyt tarve muutoksiin. Mikä on
> tavoiteltu hyöty?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/44#issuecomment-61254954.

## 

+358 44 337 5439
about.me/apoikola

**Comment by opottone** [comment]
@apoikola Joo prosessista samaa mieltä, ehkä tässä vähitellen lähestytään yhteisymmärrystä. Kai parempi sanamuoto kuin valituskelpoisen päätöksen pyytäminen olisi siis asian saattaminen viranomaisen ratkaistavaksi. Mielestäni tätä ei pitäisi tehdä automaattisesti:

1) Osa asiakirjoista on lain mukaan salaisia, eikä niitä saa luovuttaa vaikka me ja viranomainen kovasti haluaisimmekin ne julkisuuteen. Kun tässä palvelussa kuka tahansa voi pyytää mitä tahansa, niin en lähtisi siitä oletuksesta, että kieltäytyessään asiakirjan antamisesta viranomainen on väärässä ja heti pitää käynnistää muutoksenhaku.

2) Edelliseen liittyen, tavoitteena lienee vastuullinen tietojen pyytäminen; se, ettei kuormiteta viranomaisia turhanpäiten.

3) Jos hakee viranomaiselta päätöstä automaattisella ilmoituksella "Haluan asian viranomaisen ratkaistavaksi", viranomaisen päätös on aika varmasti sama kuin aiempi virkamiehen päätös. Jos taas kirjoittaa edes vähän tapauskohtaisia perusteluja hakemukselleen, lienee menestymisen mahdollisuus huimasti parempi.

4) Miten asia juridisesti edes on, voiko muutoksenhakua pyytää jo ennakoivasti ennen päätöstä?

**Comment by opottone** [comment]
Niin ja miksi viitata nimenomaan lain 13 pykälään? Laki on kokonaisuus ja lukuisat eri pykälät ovat tavanomaisenkin pyynnön kannalta relevantteja. Jos kuitenkin haluaa yhteen yksittäiseen pykälään viitata, niin eikö 9 olisi parempi?

**Comment by jaakkokorhonen** [comment]
Joo ihan hyvin voisi viitata julkisuuslakiin yleisesti. Mehän ollaan kansalaisia ja asiakkaita jotka ystävällisesti pyytää apua.

Ja ei tietenkään viljellä mitään valituskelpoisen päätöksen vaatimisen uhkaa ennen kuin tähän on syy.

**Comment by kyyberi** [comment]
Pitää ottaa sekin huomioon että viranomaisen tulee antaa pyydetyt tiedot vain jos ne on valmiina. Muussa tapauksessa kyseessä on työ joka pitäisi tehdä erikseen ja siihen ei tarvitse suostua. Alla konkreettinen esimerkki case:

Tullut "tietopyyntö" (joka ei edes ole sellainen)
"Hei,

tiedustelin tuossa aiemmin aineistoa pro gradu -työtäni varten. Olen historian opiskelija Helsingin yliopistosta ja kirjoitan tällä hetkellä pro gradu -työtäni Suomen politiikasta naisten aseman edistämiseksi Afganistanissa.

Tarvitsisin tilastoa suomalaisten osallistumisesta ISAF-operaation toimintaan, eli suomalaisen kriisinhallintajoukon (ja mahdollisesti muun henkilöstön) määrän ja naisten osuuden tuosta määrästä vuosilta 2002 - 2014.

Eli mielellään henkilöstömäärä/vuosi (2002 - 2014), josta selviäisi myös naisten osuus kokonaismäärästä.

Olisiko tällaista tietoa mahdollista saada? Riittääkö pyyntö sähköpostitse tehtynä vai pitääkö minun täyttää jokin lomake?

Ystävällisin terveisin,"

Tähän viranomainen on vastannut:
"Mikäli meillä on tällainen se voidaan luovuttaa. Mikäli sitä ei ole emme sitä valmista."

**Comment by jaakkokorhonen** [comment]
@kyyberi toi on selvityspyyntö. Ei kai toi ole tietopyyntö.fi kautta?

**Comment by kyyberi** [comment]
Ei käsittääkseni, mutta ehkä on hyvä jotenkin selventää ero käyttäjille..ehkä.

**Comment by opottone** [comment]
Mikäs tietopyynnön ja selvityspyynnön ero onkaan?

**Comment by kyyberi** [comment]
Eiköhän tietopyyntö koske valmiita dokumentteja/tiedostoja. Selvitys on prosessi. Mutta toisaalta voin olla väärässä

**Comment by opottone** [comment]
Sehän on aivan mahdollista, ettei kysyjä tarkkaan tiedä onko jotain asiakirjaa valmiiksi olemassa vaiko ei, kuten tuossa ylläolevassa sähköpostissa. Kummasta silloin on kyse? Minusta tuntuu että tällaisissa tapauksissa jaottelu tieto- ja selvityspyyntöihin vain sekoittaa asiaa.

**Comment by kyyberi** [comment]
Yhden viranomaisen tulkinta nyt ainakin tiedetään. Tuossa tapauksessa on tulkittu ettei kyseessä ole tietopyyntö. Oletan että virkamies ei ainakaan aina lähde generoimaan lisää työtä itselleen ja tulkitse toisin. Mutta aina voi kysyä ja udella, tyyli on vapaa. Lopputulos vaan saattaa sitten yllättää ja tuntua tylyltä.

**Comment by jaakkokorhonen** [comment]
Hei tutustukaapa jo tehtyihin pyyntiöhin ja kokeilkaa tehdä tietopyyntöjä itse. Huomasitteko että siellä on erittelevä luokittelukysymys, minkälasesta pyynnöstä on kyse?

**Comment by jaakkokorhonen** [comment]
Se on kansalaistaito osata esittää toimivia kysymyksiä. Tämän taidon valmentamiseksi on Tietopyyntö-facebookryhmä.

**Comment by kyyberi** [comment]
:)

**Comment by opottone** [comment]
Jotain valmennusta saattaa myös täällä githubin puolella tapahtua :)

**Comment by jaakkokorhonen** [comment]
No mielummin ei kiitos off-topic aiheita tai akateemisia väittelyitä toimeksiantojen yhteyteen, jos sen vain voi välttää.

**Comment by opottone** [comment]
Onko tuo ylläoleva keskustelu off-topic?

**Comment by jaakkokorhonen** [comment]
Ihan hyvää ideointia.

Tahtoisin kuitenkin muistuttaa että tämä on projektin tehtävälista, ja on ihan oikeaa työtä yrittää selvittää, onko pyynnön takana konkreettinen ratkaistavissa oleva reaalimaailman ongelma. Tästä ei nyt erottunut mitään sellaista mikä olisi ratkaistavissa. 

Voidaan poistaa tuo viittaus tarkkaan pykälään jos joku kirjaa korvaavan tekstin tai pyytää admin-luvitukset rekisteröidylle tunnukselleen.

Keskustelufoorumit on sitten erikseen. Avatkaa uusi taski kun saatte päätettyä, mitä pyydetään muutettavaksi. 

Kannattaa tosiaan ennen ehdoituksia kokeilla viedä yksi itse tekemänsä tietopyyntö päätökseen.
