### ISSUE TITLE
Itella e-posti integraatio tietopyyntöön

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#45]
Kaikki organisaatiot eivät halua vastata tietopyyntöihin sähköisesti. Symmetrisyyden nimissä lienee asiallista kontaktoida näitä organisaatioita vastedes - sähköpostin sijaan - Itella e-posti integraation kautta.
![1146442_10152765282220139_3802482239055273700_n](https://cloud.githubusercontent.com/assets/3482497/4833203/b2a8293e-5fa2-11e4-91b2-6bca5c2c9e0b.jpg)

**Comment by TomiToivio** [comment]
Pitäisikö tämän toimia automaattisesti vai laitetaanko joku printtaamaan tietopyyntöjä? 

Voi nimittäin olla melko mahdotonta saada kirjeenä vastauksia prosessoitua samalla tavalla automaattisesti kuin sähköpostina tulleita.

**Comment by jaakkokorhonen** [comment]
laissa Julkisuuslain 16. pykälä: "Tieto asiakirjan julkisesta sisällöstä on annettava pyydetyllä tavalla, jollei pyynnön noudattaminen asiakirjojen suuren määrän tai asiakirjan kopioinnin vaikeuden tai muun niihin verrattavan syyn vuoksi aiheuta kohtuutonta haittaa virkatoiminnalle." - eli ei pitäis joutua koskaan ottamaan vastaan papereita.
