### ISSUE TITLE
Kirjoitusvirheitä

### ISSUE THREAD

**Issue by kyyberi** [okffi/tietopyynto#46]
Kun valittu suomenkieli ja tekee tietopyynnön niin yhdessä vaiheessa on lomake jossa kysytään pyynnöntekijän postiosoitetta. Siinä on kirjoitusvirhe 
![tietopyynto-kaannosvirhe](https://cloud.githubusercontent.com/assets/1927158/4872481/6eaa9586-61e7-11e4-95e5-bce7f5b7f689.png)

**Comment by jaakkokorhonen** [comment]
Joo siellä on toista kymmentä typoa. Voisi vaikkapa työryhmäpäivänä käydä kielitekstit läpi.

**Comment by kyyberi** [comment]
No kerään tähän ketjuun ne mitä äkkiseltään löydän "verkkopalveluss" + loppuun piste
![tietopyynto-virhe2](https://cloud.githubusercontent.com/assets/1927158/4872530/40af70be-61e9-11e4-908d-53ab9e9cf5e3.png)

**Comment by kyyberi** [comment]
"Älä pyydä henklökohtaista tietoa."

![virhe1](https://cloud.githubusercontent.com/assets/1927158/4872584/b3d189a0-61ea-11e4-9f1d-9c8d1f47fa41.png)

**Comment by TomiToivio** [comment]
Onkos joku jo korjannut kirjoitusvirheet Transifexissa?

**Comment by jaakkokorhonen** [comment]
ei ilmeisesti. ainakin pitää kahlaa läpi kaikki https://github.com/okffi/tietopyynto/labels/transifex

**Comment by TomiToivio** [comment]
On siellä jotain päivittynyt: https://www.transifex.com/projects/p/froide-2/language/fi/

**Comment by jaakkokorhonen** [comment]
mikä on metapyyntö?

**Comment by jaakkokorhonen** [comment]
Kiitos @kyyberi.
Metapyyntö on joku pääkäyttäjälle menevä eskalointi. en oo nähny sellasta nappia vielä...

**Comment by TomiToivio** [comment]
Parantelin käännöksiä. IMHO tämä on enemmänkin sellainen juttu jota voi säätää suoraan Transifexissa ilman että pyörittelee kaikkia pieniä muutoksia issueissa.
