### ISSUE TITLE
Käyttöehdot sivua ei löydy

### ISSUE THREAD

**Issue by kyyberi** [okffi/tietopyynto#47]
Klikkasin http://tietopyynto.fi/tee-tietopyynto/ sivun alareunasta "Hyväksyt nämä käyttöehdot ja tietosuojaperiaatteet" kohdasta käyttöehtoja -> Page not found (404)

![tietopyynto-kayttoehdot](https://cloud.githubusercontent.com/assets/1927158/4872540/8534ba28-61e9-11e4-86c0-112e6a970e88.png)

**Comment by TomiToivio** [comment]
Tämäkin on oikeastaan Transifex-asia, käännöstiedostossa on väärät osoitteet.

**Comment by jaakkokorhonen** [comment]
@joonasp rekisteriseloste on, mitä muuta tarvitaan?

**Comment by joonasp** [comment]
käyttöehdot ja rekisteriseloste kai riittävät

2015-01-29 11:45 GMT+02:00 Jaakko Korhonen notifications@github.com:

> @joonasp https://github.com/joonasp rekisteriseloste on, mitä muuta
> tarvitaan?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okffi/tietopyynto/issues/47#issuecomment-71995988.

## 

---

My PGP public key for secure email:
http://pgp.mit.edu/pks/lookup?op=get&search=0xE269A5FFE9EDE926

**Comment by jaakkokorhonen** [comment]
Sisältödokkarit voisi kirjoittaa tänne: https://tietopyynto.hackpad.com/collection/uqaT0RpQ22P
