### ISSUE TITLE
Tietosuojaperiaatteet sivua ei löydy

### ISSUE THREAD

**Issue by kyyberi** [okffi/tietopyynto#48]
Klikkasin http://tietopyynto.fi/tee-tietopyynto/ sivun alareunasta "Hyväksyt nämä käyttöehdot ja tietosuojaperiaatteet" kohdasta linkkiä tietosuojaperiaatteet -> Page not found (404)
![tietopyynto-tietosuoja](https://cloud.githubusercontent.com/assets/1927158/4872553/d175b720-61e9-11e4-9edc-bf062697fd3e.png)

**Comment by TomiToivio** [comment]
Tämä on oikeastaan Transifex-asia, käännöstiedostossa on väärät osoitteet.

**Comment by TomiToivio** [comment]
Ehtikö joku jo tehdä näihin sisällön?
