### ISSUE TITLE
Kiirehtimisviesti puuttuu suomeksi

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#50]
My Freedom of Information request "Tietopyyntö Valtiovarainministeriön henkilörekisteriselosteista" (10/01/2014, #95) was not answered in the time defined by law and is now 4 days late. Please update me on the status of my request as soon as possible.

**Comment by TomiToivio** [comment]
Mulla ainakin tulee suomenkielinen kiirehtimisviesti näkyviin?

![tietopyynto 2](https://cloud.githubusercontent.com/assets/1176369/5673047/daaa3fa0-979f-11e4-85cf-3cba08054047.png)

> Hyvä vastaanottaja,
> 
> Tietopyyntööni "blablalba" (9.1.2015, #168) ei vastattu lain määrittelemässä ajassa ja se on nyt 1 päivä myöhässä.
> Olkaa hyvä ja kertokaa minulle tietopyyntöni tilasta niin nopeasti kuin mahdollista.
> 
> Ystävällisin terveisin,
> Tomi Toivio
