### ISSUE TITLE
OSError: Tietojen peittämistoiminto crashaa peittämisen jälkeen julkaistaessa

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#51]
Kts. liite

![screenshot 2014-11-24 12 05 42](https://cloud.githubusercontent.com/assets/3482497/5164265/4ad880c4-73de-11e4-884d-7c3ce0f0f2f0.png)

**Comment by TomiToivio** [comment]
Näyttäisi olevan pelkkä permission -ongelma... Vaihtaa permissiot niin redaction toimii.

**Comment by TomiToivio** [comment]
Oletko testannut crashaako vieläkin?

**Comment by jaakkokorhonen** [comment]
toimii
