### ISSUE TITLE
How to continue the same FOI request to another email address

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#52]
When answering a referred FOI request, i can still only send the message from froide to the original booking office (kirjaamo), not to the referred public officer.
![screenshot 2014-12-22 16 27 50](https://cloud.githubusercontent.com/assets/3482497/5526024/c622e40c-89f7-11e4-81bc-9888d1d264e1.png)

**Comment by jaakkokorhonen** [comment]
For example this was forwarded to another ministry http://tietopyynto.fi/r/84

**Comment by TomiToivio** [comment]
Viestin lähettäneen viranomaisen voi vaihtaa.

![tietopyynto](https://cloud.githubusercontent.com/assets/1176369/5672876/c03fa6d4-979d-11e4-97dd-aa8faecf52e0.png)

**Comment by TomiToivio** [comment]
Ja viestejä voi myös lähettää niihin eri sähköpostiosoitteisiin, joista tulee vastauksia. 

![tietopyynto 1](https://cloud.githubusercontent.com/assets/1176369/5672913/2004f7fe-979e-11e4-89a5-ac22bfb282ad.png)

**Comment by jaakkokorhonen** [comment]
Piti osata klikata "(muutos)".
Vaihdoin Transifexiin "(vaihda vastaanottava viranomainen)"

**Comment by jaakkokorhonen** [comment]
Jos vaihdan adminissa viranomaisen, sen jälkeen viestit alkaa menemään uudelle ohjatulle osoiteelle.
