### ISSUE TITLE
Julkaise rekisteriseloste etusivulla

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#53]
Julkaise  http://tietopyynto.fi/admin/foisite/foisite/1/ etusivun footerissa.

**Comment by jaakkokorhonen** [comment]
@TomiToivio katotko tätä?

**Comment by TomiToivio** [comment]
Siis tällä tavalla omalla sivullaan ilmeisesti: http://tietopyynto.fi/apua/Tietoja%20palvelusta/

Admin-editori ei näytä toimivan, näitä pitää kirjoittaa suoraan templaatteihin.
