### ISSUE TITLE
How to forward requesta in between organisations?

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#56]
Ok löyty mistä vastaanottajan organisaatiotiedon saa vaihdettua, mutta kun yritän vastata, lisätty organisaatio ei näy vastaanottajissa. VNK:n Miikan maili vaan näkyy kuin olis STM organisaatiossa.

Lisäksi, toi mailitemplate on edelleen englanniksi.

Esimerkkicase http://tietopyynto.fi/r/84

![screenshot 2015-01-09 04 05 38](https://cloud.githubusercontent.com/assets/3482497/5674541/d63f7b78-97b4-11e4-8949-ed74da223f18.png)
![screenshot 2015-01-09 04 05 26](https://cloud.githubusercontent.com/assets/3482497/5674542/d646dd64-97b4-11e4-956f-3576ef7609e7.png)

**Comment by jaakkokorhonen** [comment]
Tossa toinen mikä pitäis forwardoida http://tietopyynto.fi/r/86

**Comment by TomiToivio** [comment]
Voihan sen vastaanottajan vaihtaa Sisäministeriöksi?

![tietopyynto](https://cloud.githubusercontent.com/assets/1176369/5676486/3719a8ae-97df-11e4-97ba-bcf58cdcffb9.png)

**Comment by TomiToivio** [comment]
Mitäs jos viranomaisen vain vaihtaa administa? 

![muokkaa tietopyynto django-sivuston yllapito](https://cloud.githubusercontent.com/assets/1176369/5917096/aef7b50a-a621-11e4-9b09-03882032df60.png)
