### ISSUE TITLE
add status options

### ISSUE THREAD

**Issue by joonasp** [okffi/tietopyynto#59]
mahdollista asian merkitseminen tiloihin:
- "haettu muutosta viranomaiselta"
- "haettu muutosta hallinto-oikeudesta"
- "haettu muutos korkeimmasta hallinto-oikeudesta"

**Comment by jaakkokorhonen** [comment]
Eks noit saa lisättyä?

**Comment by TomiToivio** [comment]
Kaipa niitä voi lisätä?

**Comment by TomiToivio** [comment]
Olisivatko nämä tilat nyt käytännössä avoimia tietopyyntöjä, kuten "Odottaa vastausta": http://tietopyynto.fi/tietopyynnot/odottaa-vastausta/

**Comment by TomiToivio** [comment]
Eli jos sinne lisää vain uusia avoimen tietopyynnön tiloja "Muutosta haettu viranomaiselta" jne.

![freedom of information requests - froide](https://cloud.githubusercontent.com/assets/1176369/5898129/f262d658-a554-11e4-8332-c458ed17f064.png)

**Comment by joonasp** [comment]
Joo ne on uusia avoimen tietopyynnön tiloja.

**Comment by TomiToivio** [comment]
Tarttisko noihin kivan kuvakkeen, kuten muihinkin tiloihin. :) 

![tietopyynto](https://cloud.githubusercontent.com/assets/1176369/5916601/91a48f56-a61b-11e4-9dd7-bf84f827849a.png)

**Comment by TomiToivio** [comment]
Oikeastaan Froiden logiikalla näiden pitäisi olla suljettujen tietopyyntöjen tiloja ("resolution"). Nyt noi tilat joutuu nimittäin asettamaan administa.
