### ISSUE TITLE
Welcome to tietopyyntö.fi -team

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#6]
Target: Finnish Freedom of Information request site tietopyyntö.fi -up and running

Possible ways to contribute
- Translate and test / review translations https://www.transifex.com/projects/p/froide/
- Setting up the production server
- Collecting the information of public bodies in Finland https://github.com/okffi/froide/issues/1
- Design the UI theme
- Testing and giving feedback

You can write to this thread if you are interested to join. We keep the communication mainly in English because of the the international collaboration, but Finnish is allowed also if you feel more comfortable with that.

**Comment by tuukkajs** [comment]
im in.

**Comment by tuukkajs** [comment]
What can be done regarding the project at the moment? 

I browsed through the various threads and sites but didn't quite grasp what are the things that would help the project move towards completion...

**Comment by pe3** [comment]
@tuukkajs that is a bit unclear for me too - ping @apoikola

**Comment by apoikola** [comment]
at the moment we are planning to setup production server to Finland and Sweden at the same time. I added @jaakkokorhonen and @tuukkajs to a fb-chat for fast iteration of to-do's.

**Comment by jaakkokorhonen** [comment]
@tuukkajs feel free to start testing on making FOI requests in http://tietopyynto.fi/, and opening issues here if bugs are found.

**Comment by opottone** [comment]
Viranomaiset -listaa lienee syytä vähän karsia niin että siellä olisi vain viranomaisia. Suurin osa mainituista ry:istä tuskin käyttää julkista valtaa (mikä on tosin hieman epämääräinen käsite). 

Viranomaiset -listassa on Ahvenanmaan maakuntahallitus ja useampi Ahvenanmaan kunta. Näille ei ole syytä lähettää tietopyyntöjä yleisellä julkisuuslakiin viittaavalla johdantomallilla, sillä julkisuuslaki ei ole voimassa Ahvenanmaalla (paitsi kansainvälisiä velvoitteita ja EU-asioita koskevien asiakirjojen osalta). Sen sijaan maakuntaa koskee maakuntalaki yleisten asiakirjojen julkisuudesta (1977:72), ja tietysti perustuslain yleisluontoinen määräys.

**Comment by jaakkokorhonen** [comment]
Avattu #43.

**Comment by opottone** [comment]
Projektin etusivulla [https://github.com/okffi/tietopyynto] ohjattiin osallistumaan keskusteluun tässä ketjussa, kun taas viereisen ketjun kommenteista [https://github.com/okffi/tietopyynto/issues/44#issuecomment-61427759] ymmärsin että keskustelu pitäisi käydä facebookissa; githubin puolella vain pidetään tehtävälistaa. Tässä jäi vähän epäselväksi missä pitäisi keskustella ja onko käytännössä mielekästä yrittää osallistua jos ei ole facebookissa.

**Comment by apoikola** [comment]
Joo tämä issue avattiin aikana, kun projektissa ei ollut ensinkään Facebookryhmää, eikä mitään. Mielestäni on hyvä, että on myös FB:n ulkopuolisia kanavia keskusteluihin, mutta Githubin luonteesta johtuen täällä ollaan ratkaisuhakuisia, joten issuessa pitää olla ongelma, jonka ratkaisuusn keskustelu tähtää. Yleiset keskustelut palvelun luonteesta, markkinoinnista, rahoituksesta tms. ei-teknisestä / ei-sisällöllisestä vähän huonosti istuvat Github-meininkiin, mutta FB-tunnuksen omaaminen ei mielestäni saa olla edellytys osallistumiselle.

**Comment by jaakkokorhonen** [comment]
Joo juurikin näin. Ei-facebookkailijoille on okffi Slack.

**Comment by jaakkokorhonen** [comment]
Keskustelu jatkuu facebookissa.
