### ISSUE TITLE
Vastaanotetut viestit ja liitetiedostot ei aina tallennu

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#65]

**Comment by joonasp** [comment]
kun julkaisen tietopyynnön vastaukset, niin liite ei toimi. esim. http://tietopyynto.fi/files/foi/552/Osakassopimus_julkinen.pdf

**Comment by hylje** [comment]
Toimii nyt. Liitteiden käyttöoikeuksia ja julkisuutta ei tällä hetkellä tarkisteta, se olisi vähän monimutkaisempi korjaus.
