### ISSUE TITLE
Ideas for the UI design

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#7]
We are planning to make new UI theme for the Finnish implementation of the Froide platform. Currently the theme is the original theme used in https://fragdenstaat.de/ . Feel free to give any suggestions.

**Comment by apoikola** [comment]
A theming guide is here:
http://froide.readthedocs.org/en/latest/theming/

A template theme can be found here:
https://github.com/okfn/froide-theme

The FragDenStaat.de theme is located here:
https://github.com/okfde/fragdenstaat_de

**Comment by jaakkokorhonen** [comment]
This is old ui framework already, django is being rewritten, so we'll just stick to css changes.
