### ISSUE TITLE
Tietopyynnön #619 liitteet Not Found

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#70]
http://tietopyynto.fi/tietopyynto/viraston-diaariote-verkkokauppacom-asioista-vuosilta-2012-ja-2013/ sanoo liitteissä:
Not Found
The requested URL /files/foi/619/Liite_1_1_Kooste_verkkokauppa.com_ilmoituksista_vuosilta_2012-2014.DOC was not found on this server.

http://tietopyynto.fi/files/foi/619/Liite_1_1_Kooste_verkkokauppa.com_ilmoituksista_vuosilta_2012-2014.DOC

**Comment by jaakkokorhonen** [comment]
Sama tässä http://tietopyynto.fi/files/foi/675/liite-28-ministeri-alexander-stubbille-toimitettu-muistio-1092015.pdf

**Comment by hylje** [comment]
Uudet liitetiedostot menivät eri hakemistoon. Nyt hakemistot on yhdistetty ja vain sitä samaa hakemistoa käytetään jatkossa.
