### ISSUE TITLE
Palvelimenne hylkäsi sähköpostimme. Ilmeisestikin kokorajoitteen pohjalta

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#71]
Voiko sähköpostipalvelimen kokorajaa nostaa? http://tietopyynto.fi/files/foi/683/EivoitutoimittaaReVSTietopyyntnne.eml

**Comment by hylje** [comment]
Diagnostiikan perusteella ongelma on lähettäjän SMTP-palvelimessa. Tietopyynnön Dovecot ottaa vastaan mielivaltaisen suuria liitetiedostoja.
