### ISSUE TITLE
Tietoa Apua Käyttöehdot Tietosuojakäytännöt -linkit rikki

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#75]

**Comment by jaakkokorhonen** [comment]
Tälläsethän on ehdotettu https://tietopyynto.hackpad.com/collection/uqaT0RpQ22P

**Comment by hylje** [comment]
Tekninen toteutus on valmis, näiden sivujen tekstiä voi muokata adminin tekstisivut-osiossa.
