### ISSUE TITLE
Expert mode

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#76]
Helpotettu formi, josta turha "Valitse tietopyynnön tyyppi " kyselyt pois
Samoin "
Lakitekninen selitys:
Julkisuuslaki
Tärkeitä huomioita:
    Kirjoita pyyntösi yksinkertaisella ja tarkalla kielellä.
    Pyydä tiettyjä dokumentteja tai tietoa.
    Pidä se tarkkana ja lyhyenä.
    Tämä sivusto on julkinen. Kaikki mitä kirjoitat tulee olemaan julkista.
    Älä sisällytä henkilökohtaista tietoa pyyntöösi.
    Älä pyydä henklökohtaista tietoa."
pois.

Expert mode -täppä jonka admin laittaa päälle.
Muutos, että Tee tietopyyntö -painike johtaa helpotettuun formiin.

**Comment by hylje** [comment]
Nyt käyttäjällä on expert-lippu jonka admin voi kytkeä päälle ja pois. Jos lippu on päällä, tietopyyntölomakkeesta häviää "onko tietopyyntö?"-steppi ja pari avustavaa tekstiä.
