### ISSUE TITLE
Lain tekstejä rikki

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#80]
Tässä voisi olla visiojaarvot url niin että avaa linkin uudessa ikkunassa.

![screenshot 2016-01-30 16 11 13](https://cloud.githubusercontent.com/assets/3482497/12696182/36e8dc52-c76c-11e5-95d4-47ffe1730af4.png)

Ja tässä on "ystävällisin terveisin" kahdesti. Preview näyttää että "ystävällisin terveisin" -teksti ei olisi mukana viestissä.

![screenshot 2016-01-30 16 10 27](https://cloud.githubusercontent.com/assets/3482497/12696184/4576ded6-c76c-11e5-86a5-b90cf2679254.png)

**Comment by hylje** [comment]
Toi ykkösteksti tulee käännöslauseista, eli linkki-html pitäisi löytyä sieltä. `<a href="http://okf.fi/visiojaarvot" target="_blank">` jne.

**Comment by hylje** [comment]
Ystävällisin terveisin-teksti esiintyy nyt vain kerran.
