### ISSUE TITLE
500 - Palvelinvirhe lähetettäessä

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#82]
http://tietopyynto.fi/tietopyynto/tyomarkkinajarjestojen-hallitukselle-jattaman-elakeratkaisun-dokumentit-1/send/message/#write-message

**Comment by hylje** [comment]
Sähköpostin lähettäminen heittää virhettä. `SMTPRecipientsRefused: {'': (501, '5.1.3 Bad recipient address syntax')}`

**Comment by hylje** [comment]
Tämä tosiaan johtuu käyttäjästä, jolla on tyhjä sähköpostiosoite. Sellaisen voi luoda vain ylläpitopaneelista. Yksi sellainen on korjattu, joten suljen tämän.
