### ISSUE TITLE
viestin liitteet antaa 404

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#83]
http://tietopyynto.fi/tietopyynto/diaariote-helsingin-tietopyynnoista/  1. helmikuuta 2016 kello 10.33  viestin liitteet antaa 404  http://tietopyynto.fi/files/foi/741/Tietopyynt2014-009970ja2014-009917vastaus.pdf

**Comment by jaakkokorhonen** [comment]
ja toinen http://tietopyynto.fi/tietopyynto/liikenneviraston-luonnonvarakeskukselle-valittaman-tietopyyntoni-dokumentit/

**Comment by hylje** [comment]
Liitteet on tallessa, mutta vanhassa sijainnissa. Näemmä taustaprosessin voisi käynnistää uudelleen, jospa se tajuaisi sitten minne ne pitää laittaa.

**Comment by hylje** [comment]
Kappas, vanha taustaprosessi oli crontabissa. Päivitän sen käynnistämään uuden.

**Comment by hylje** [comment]
Liitteet löytyvät nyt.

**Comment by jaakkokorhonen** [comment]
sweet
