### ISSUE TITLE
og image ei näy sosiaalisessa mediassa

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#84]
![screenshot 2016-02-10 13 08 09](https://cloud.githubusercontent.com/assets/3482497/12945629/723076a6-cff7-11e5-874f-463192932e6a.png)

**Comment by hylje** [comment]
Nyt on toi etusivun mappikuva og:imagessa. Facebookin debuggeri näyttää tyytyväiseltä. 

<img width="479" alt="screen shot 2016-02-11 at 17 11 49" src="https://cloud.githubusercontent.com/assets/277733/12979912/9a56d706-d0e2-11e5-8f5e-e83e6f5d21df.png">
