### ISSUE TITLE
OG title ja description

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#88]
Nyt jaot näyttää tältä:
![screenshot 2016-02-22 20 14 09](https://cloud.githubusercontent.com/assets/3482497/13227753/e365b20c-d9a0-11e5-8413-7c3732a23ca1.png)
Saisko Otsikko-kentän OG-titleen dynaamisesti, ja varsinaisen keltaisella maalatun pyyntökentän OG-descriptioniin dynaamisesti? 
![screenshot 2016-02-22 20 14 22](https://cloud.githubusercontent.com/assets/3482497/13227754/e36605d6-d9a0-11e5-81f3-9b2dac261451.png)

**Comment by hylje** [comment]
Otsikko ja kuvaus tulevat nyt tietopyynnön og-tageihin. Lisäksi tietopyynnön kuvausta voi muokata.
