### ISSUE TITLE
TEST if Django oauth api could be used

### ISSUE THREAD

**Issue by apoikola** [okffi/tietopyynto#9]
Mitä tunnuksia käytetään?

**Comment by TomiToivio** [comment]
Omasta mielestäni isoimpien ja yleisimpien OAuth-palveluntarjojajien käyttö madaltaisi radikaalisti osallistumiskynnystä, eli populismin vuoksi Facebook ja Google.

**Comment by TomiToivio** [comment]
Tämän saa kyllä toimimaan Booktypen puolella: http://django-social-auth.readthedocs.org/en/latest/

Laitoin providereiksi GitHubin, Googlen, Twitterin ja Facebookin.

Rekisteröityminen toimii, se osaa myös automaattisesti yhdistää autentikaation olemassaolevaan käyttäjätiliin, jos provider antaa olemassaolevan accountin sähköpostiosoitteen, mutta ainakaan Twitteristä ei taida saada mitenkään sähköpostiosoitetta. 

Ilman rekisteröitymisen muokkaamista esimerkiksi Twitter tekee näppärästi käyttäjätilejä, joilla ei ole sähköpostiosoitetta ja salasanaa, eli käyttäjä ei voi ilman kikkailua logata sisään mitenkään muuten kuin Twitterillä.

**Comment by TomiToivio** [comment]
Django Social Auth ei ainakaan toimi pienellä vaivalla Froidessa.

**Comment by jaakkokorhonen** [comment]
Let's ask @stefanw when we get a chance.

**Comment by TomiToivio** [comment]
Django Social Auth jämähti siis siihen ettei Froide osannut tulkita palveluntarjoajilta tulevia viestejä.

Sen sai aika pienellä vaivalla toimimaan Booktypessä, mutta Froide näyttäisi olevan vaikeampi tapaus.

**Comment by TomiToivio** [comment]
Python Social Authin sai kyllä toimimaan: http://python-social-auth.readthedocs.org/en/latest/

Siis Facebookin ja GitHubin. Googlea en saanut vielä. Mitä tähän yleensä kannattaa laittaa?

Twitter ei kelpaa, koska pitää autentikaatiossa pitää saada sähköpostiosoite.

Autentikaatio toimii näin:
1) Jos sähköpostiosoitteella on jo käyttäjätili, sosiaalinen autentikaatio liitetään siihen.
2) Jos sähköpostiosoitetta ei vielä ole, luodaan uusi käyttäjätunnus.

**Comment by apoikola** [comment]
Google olisi hyvä, mutta FB Githubkin riittää jo pitkälle
