### ISSUE TITLE
Miten tietopyynnön kohde vaihdetaan?

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#93]
Miten tämä reitietään Helsingin kaupungin opetusvirastolle, osoitteeseen  opetusvirasto@hel.fi? http://tietopyynto.fi/tietopyynto/wilma-jarjestelman-rekisteriseloste-hankintasopimuks-ja-datan-lisenssi/

**Comment by jaakkokorhonen** [comment]
Tässä toinen että pitäisi kiirehtiä http://tietopyynto.fi/tietopyynto/gm-maissi-1507-viljelyluvan-puoltamisen-asiakirjat/

**Comment by hylje** [comment]
Onko tässä kyse jostain syvällisemmästä kuin viranomaisen sähköpostiosoitteen muuttamisesta tai tietopyyntöön liittyvän viranomaisen muuttamisesta? Niitä voi korjailla ylläpitopaneelista suoraan.

**Comment by jaakkokorhonen** [comment]
joo ajattelin että voisi, mutta en osannut. täytyy testata, ja kirjottaa joku ohje.

**Comment by hylje** [comment]
Huomenna vois kattoa adminijuttuja

**Comment by jaakkokorhonen** [comment]
https://tietopyynto.hackpad.com/Ohje-TrYpWNbsMpY#:h=Uuden-vastaanottajan-lis%C3%A4%C3%A4mine
